### ISSUE TITLE
Custom Authorization

### ISSUE THREAD

**Issue by observant2** [shopware/platform#155]
Hello there!
We want to integrate our shop into an existing website which authenticates via an existing API endpoint.
We want to have a Single Sign On, so the user can go from the normal page to the online shop without having to log in again.

What is the recommended approach here?

I looked at `src/Storefront/Framework/Routing/StorefrontSubscriber.php` and my approach would be to create my own subscriber listening to `KernelEvents::REQUEST` with higher priority than the priority of the `StorefrontSubscriber.php`, do my login logic there and skip the rest of the listeners.

But I feel like that approach is a very untidy one and can break easily. Any ideas for a cleaner way to do this?

**Comment by moorl** [comment]
@itmuckel 
Maybe i could Help. What kind of SSO Service do you use?

**Comment by janbuecker** [comment]
Hey, we can implement an interface for the `AccountService` to make replaceable. I've created an issue for this request (https://issues.shopware.com/issues/NEXT-4755).

To require a login for every route, you can create an EventListener which listens to the `KernelEvents::REQUEST` or `KernelEvents::CONTROLLER` and checks if the user is authenticated - otherwise redirect him to the login.

**Comment by moorl** [comment]
@janbuecker 
Is it possible to add "customFields" for AccountRegistrationService->mapCustomerData()?

**Comment by jenskueper** [comment]
Hey,
in terms of security i see an issue to allow setting customFields from the outside but if you have a look at the mapCustomerData method, an event is thrown to add addituinal data e.g. customFields.

https://github.com/shopware/platform/blob/master/src/Core/Checkout/Customer/SalesChannel/AccountRegistrationService.php#L254
