### ISSUE TITLE
Email address from basic settings overrides the mailer settings sender address

### ISSUE THREAD

**Issue by mgwestwerk** [shopware/platform#1639]
**Description**  
When both the shop owner's email in basic information and the sender address in the mailer settings are configured, the first one takes precedence. Depending on the two addresses and the used mail server this can cause the emails to be rejected

**Possible Solution**  
Change the order to prefer the mailer sender address.

**Additional context**  
https://github.com/shopware/platform/blob/43b7da3187e6e5ded127382ea9bfd0d8c3c3872e/src/Core/Content/MailTemplate/Service/MailService.php#L233
https://github.com/shopware/platform/blob/43b7da3187e6e5ded127382ea9bfd0d8c3c3872e/src/Core/Content/MailTemplate/Service/MailService.php#L237

**Comment by JoshuaBehrens** [comment]
Related https://github.com/shopware/platform/pull/684

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
