### ISSUE TITLE
Media upload wrong time

### ISSUE THREAD

**Issue by JoostWan** [shopware/platform#1643]
**Description**  
Create a custom field with media type for category. Upload a PDF file. The PDF file get the upload date in the database table with UTC time. In our case 2021-02-12 13:11:59.089. 

Shopware uses the time to create a folder on the server for the pdf file. It will convert the date/time to **datetimeimmutable**. This function in Shopware wil respect the timezone difference. In our case 1 hour. 
So the folder created on the server is created with `2021-02-12 13:11:59.089` but Shopware uses `2021-02-12 14:11:59.089` for the PDF link. Because of this difference the pdf link is not working. 
When we changed the date in the database to `2021-02-12 14:11:59.089` we get the correct link on the frontend. 

`https://domain.nl/media/ef/8f/78/1613131919/pdffile.pdf`

We uses this function for creating the link. 

https://docs.shopware.com/en/shopware-platform-dev-en/how-to/custom-fields-media-type

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
