### ISSUE TITLE
NEXT-13900: Category sorting in Administration behaving buggy

### ISSUE THREAD

**Issue by runelaenen** [shopware/platform#1655]
**Description**  
Sorting the categories in the backend works really buggy, and switches places for multiple categories.
I've overdone it in the video to make it clear, but when working slow, everything works as expected, but as soon as you work a bit quicker, the sorting of the other categories does not remain correct.

**Additional context**  

https://user-images.githubusercontent.com/3930922/108322335-a410ea00-71c5-11eb-8325-81af246f591b.mov

_I tried fixing this problem myself before creating a bug report, but it became very obvious that I'm not a Vue programmer 😅_

**Comment by runelaenen** [comment]
Actually, on rewatching my video I noticed that the first slow drag is also buggy  🙈 
(take a look at the Tools category, which switches places while it shouldn't)

**Comment by Wusa-Dev** [comment]
I can confirm this behaviour. Its really frustrating. Maybe you could create an issue in the Shopware Issue Tracker? 
https://issues.shopware.com/

**Comment by runelaenen** [comment]
https://issues.shopware.com/issues/NEXT-13900

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
