### ISSUE TITLE
validate() Method in NavigationRoute blocks functionality

### ISSUE THREAD

**Issue by Blur-Creative** [shopware/platform#1663]
**Description**  
If you try to Enter a Category / Navigation that isn't assigned to a SalesChannel Content Entry Point (eg Footer Menu or Service Menu) a 404 CategoryNotFoundException will be thrown.

**Possible Solution**  
kill the `validate()` Method here https://github.com/shopware/platform/blob/656c82d5232c87b75e1d6b42bd6493d674807791/src/Core/Content/Category/SalesChannel/NavigationRoute.php#L105 and you can Enter any active Category in the Frontend.

**Additional context**  
I try to provide a new Entry Point in the Frontend for a Category Tree and link to each Category in the Frontend.
This new Category Tree should be detached from the SalesChannel "Footer Menu" and Service Menu" Entry Points.  
So that it is possible to provide a whole new Entry Point. With the current implementation of the `validate()` Method this is impossible.
In my Opinion the System should be flexible to set Custom Entry Points for Category Collections.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
