### ISSUE TITLE
properties/characteristics output only name in span object

### ISSUE THREAD

**Issue by sandra-walker** [shopware/platform#1674]
Characteristics/properties of catalogue images does not output any image,
just a span object with the name.

See screenshots for more detail.
![symbole-GHS](https://user-images.githubusercontent.com/37797118/109466538-2755f980-7a6a-11eb-898b-7d27897ac22c.PNG)
![span](https://user-images.githubusercontent.com/37797118/109466542-2b821700-7a6a-11eb-946b-a84edd482166.PNG)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
