### ISSUE TITLE
PHP8 support in 6.4 but composer.json only allows PHP 7.4

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1678]
**Description**  
Same issue here as in production template: https://github.com/shopware/production/issues/91

This is also the case for `shopware/core` etc.

**Possible Solution**  
Adjust composer.json to allow `^7.4 | ^8.0`.

Related issues: https://github.com/shopware/platform/issues/1679, https://github.com/shopware/production/issues/91, https://github.com/shopware/production/issues/90

**Comment by shyim** [comment]
Is fixed since yesterday

**Comment by AndreasA** [comment]
@shyim Great thanks.

**Comment by AlexBachmann** [comment]
@shyim I'd like to reopen this ticket. Shopware 6.4 still has a dependency on `"doctrine/inflector": "1.3.1"` which is only compatible with PHP 7. It's only used by `Shopware\Core\Framework\DataAbstractionLayer\DefinitionValidator` and could be upgraded to the newest version 2.0.3 pretty easily in my opinion. 

Up until then, it's not really possible to use PHP 8, since composer starts complaining.

**Comment by mitelg** [comment]
there is already an open PR https://github.com/shopware/platform/pull/1858
