### ISSUE TITLE
Do not override PHP version in composer.json 

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1679]
**Description**  
Not that big an issue as with the shopware production template as it is not the root `composer.json`.

You really should not override the PHP version in the composer.json that completely bypasses local requirement checks.

See also production template issue: https://github.com/shopware/production/issues/90
And related issues: https://github.com/shopware/production/issues/91, https://github.com/shopware/platform/issues/1678

This is also the case for `shopware/core` etc.

**Possible Solution**  
Adjust composer.json and if necessary your installation bundler scripts.

**Comment by shyim** [comment]
related to https://github.com/ongr-io/ElasticsearchDSL/issues/344

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
