### ISSUE TITLE
Hardcoded app.scss is loaded in HMR mode

### ISSUE THREAD

**Issue by gijsroge** [shopware/platform#1680]
When you run the "hot" npm script webpack will auto inject `src/scss/base.scss` regardless of your theme.json configuration. If one would like to not load the entire Frontware styles, for example if you want to use Bootstrap 5 instead of the outdated version, this would currently not be possible.

https://github.com/shopware/storefront/blob/trunk/Resources/app/storefront/webpack.config.js#L101

Maybe i'm missing something :D

**Comment by tomgraphitas** [comment]
Hey @gijsroge, did you ever find a solution to this? I have also found that app.scss is loaded regardless of my theme.json file when using HMR.

**Comment by flmuel** [comment]
It would be great if the injection of base.scss while running HMR would respect the theme.json configuration of the activated theme

**Comment by flmuel** [comment]
Removing [this passage](https://github.com/shopware/storefront/blob/trunk/Resources/app/storefront/webpack.config.js#L111-L122) fixes my problems and still works with manipulating default theme

**Comment by flmuel** [comment]
Removing [line 115 in webpack config](https://github.com/shopware/storefront/blob/trunk/Resources/app/storefront/webpack.config.js#L115) fixes my problems and still works with manipulating default theme

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
