### ISSUE TITLE
Repeat Import of Customers results in duplicate Shopware Entities while customerNr is the same.

### ISSUE THREAD

**Issue by vardumper** [shopware/platform#1681]
**Description**  
When importing customers through the same CSV file twice, I end up with duplicate customers, when I don't give a autoIncrement but only a customerNr. This is a somewhat odd behavior since the customerNr is something I can make sure is unique, while I cannot control uniqueness of autoIncrement IDs especially when importing from multiple databases, standalone and/or satellite stores.

**Possible Solution**  
Have the ImportExport consider customers unique when the same customerNr is given without depending on unique autoIncrement IDs. This would eliminate the need of extra-added complexity of importing.

** Additional Context **
In my specific scenario customerNrs look like C10000347576 or K100035438 or C2000387436 which identifies the sales channel and market (country) of customers to our support staff. All 3 customers could have the same auto increment ID in our old shop installations. Also, it wouldn't feel right to put alphanumeric values in a autoIncrement column. By removing the prepending letter, I would again loose uniqueness.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
