### ISSUE TITLE
Newly uploaded category menu image applied to multiple categories

### ISSUE THREAD

**Issue by gRoberts84** [shopware/platform#1691]
**Description**  

When uploading a new menu image to a category, if any siblings do not already have an image applied, it will show the newly uploaded image, even if it was not uploaded to that category. 

Refreshing and going back to the siblings will show an empty image and the correct image against the correct category.

**Possible Solution**  

It appears when uploading a new image, saving and moving to the next sibling, if the next sibling does not have an image it does not clear the uploaded image until you refresh.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
