### ISSUE TITLE
Support ability to hide default theme fields

### ISSUE THREAD

**Issue by gRoberts84** [shopware/platform#1692]
**Description**  

Whilst some developers may want to develop themes to be reused across multiple websites, needing the ability to change the logos, fonts and colours etc, I am building a theme for a client and won't be using those fields. 

I have attempted to override the fields via theme.json by setting the `editable` property to false, however this is ignored.

It would be useful if it were possible to hide fields and when hidden, the default value provided will be used unless overridden at the theme level.

**Example**  

```
"config": {
  "fields": {
    "sw-color-brand-primary": {
      "editable": false
    }
  }
}
```

**Comment by ILCAI** [comment]
I guess you have tried to re-compile the theme. Anyways, I did the same as you and I would like to achieve the same behaviour.
The editable flag does not hide the fields, but it does prevent editing.

It would be very handy to completely hide fields. I agree with you.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
