### ISSUE TITLE
Unable to delete advanced prices due to media bar covering actions button

### ISSUE THREAD

**Issue by gRoberts84** [shopware/platform#1698]
**Description**  

When trying to delete some advanced prices from a test product, I noticed that there doesn't appear to be any padding/margins to account for the absolutely positioned media bar.

This unfortunately prevents me from actually being able to delete them.

**Additional context**  

![image](https://user-images.githubusercontent.com/348184/110681187-740ba400-81d1-11eb-8df6-cd1576db8692.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
