### ISSUE TITLE
Overwriting translations does not work

### ISSUE THREAD

**Issue by Schrank** [shopware/platform#1700]
**Description**  
I want to include my own translation and overwrite a default translation, like `checkout.addressHeader`. But that does not work, because the default translation is loaded last.

Or in more words:
Shopware loads first all translations which have a PHP file laying nearby (not sure of the order here) and then it loads all Generic translations files (not sure of the order here as well). The important point is the loading order is not defined.

**Possible Solution**  
Every translation gets a priority which is 0 by default and one can overwrite it in their own implementation of `SnippetFileInterface`. And then it is ordered before the snippets are loaded

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
