### ISSUE TITLE
Registration form: company fields will not displayed

### ISSUE THREAD

**Issue by jd297** [shopware/platform#1709]
**Description**  
Hello I have the follwing scenario: Create a "Customer group". Then enable the "Toggle registration form" switch and enable "Only companies can sign-up". After that set a sales channel under "Available Sales Channels". Then make sure you selected the Customer group that you have created under "sw/sales/channel/detail/.....". Ok, now go back to the new customer group and copy the URL from the sales channel. E.g. https://meinshop.de/Ich-bin-ein-Geschaeftskunde.

Now if you look at this register page there are no company form fields any more. In Version "6.3.3.0" it works but in the new Version "6.3.5.2" it does not work. The fields was previously displayed in the address section.

**Possible Solution**  
I have seen code changes in the register template files maybe something screwed up there. I also discovered that the company fields are hidden (look at the screenshots ;)

**Additional context**  
![field-is-hidden](https://user-images.githubusercontent.com/56673596/111178350-5496c180-85ab-11eb-8689-48abc89bbee4.png)
![older-version](https://user-images.githubusercontent.com/56673596/111178358-5791b200-85ab-11eb-9235-344e88a83a55.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
