### ISSUE TITLE
Saving cms page error on different language

### ISSUE THREAD

**Issue by runelaenen** [shopware/platform#1712]
**Description**  
When saving a CMS page, which has custom fields, in a different (non default) language, shopware returns an 500.

**Possible Solution**  
Allow null for name, as it should fall back on the main language.

**Additional context**  
```
detail: "An exception occurred while executing 'INSERT INTO `cms_page_translation` (`cms_page_id`, `language_id`, `name`, `custom_fields`, `created_at`) VALUES (?, ?, ?, ?, ?)' with params ["\xc2\x03\x2d\x35\x3e\x80\x46\xa4\xae\xa4\x5e\xdd\x69\xaa\xd0\x56", "\x56\x9f\xf2\x9d\xee\x9b\x40\xd9\xb0\x46\x80\x7f\x02\x3f\xe2\x9c", null, "{\"custom_field\":false}", "2021-03-17 09:06:32.771"]:↵↵SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null"
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
