### ISSUE TITLE
Storefront Language switcher - Flag codes are inverted (country is used for language and language for country)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1713]
**Description**  
Currently the country/language flags in the storefront language switcher are inverted:
https://github.com/shopware/platform/blob/trunk/src/Storefront/Resources/views/storefront/layout/header/actions/language-widget.html.twig#L42

The country part of a locale is the second `1` and the language one is the first `0`.
This results in a flag being called `country-en`. Which is wrong, it should be `country-gb` and `language-en` or `country-us` and `language-en`.

**Possible Solution**  
- Adjust the parts to use the correct ones.
- Adjust the scss classes accordingly.
- Maybe differentiate between country-us and country-gb flags too.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
