### ISSUE TITLE
HTML lang tag uses the snippet set locale instead of the locale from the language

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1714]
**Description**  
Currently the lang from the HTML tag uses app.request.locale which is basically the one used for the snippet set.

However, this might be a different in contrast from the locale used/assigned to the sales channel. So the easiest solution would be to load the current locale code from the sales channel context. However, even better would be, if the sales channel context contains the locale code too and not just the ID as it is needed nearly everywhere anyway.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
