### ISSUE TITLE
Promotion/discount fixed item price - Missing advanced/currency based pricing button in admin

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1723]
**Description**  
All other promotion types provide the advanced/currency based pricing. This button seems to be missing for the promotion fixed item price. However, values configured in it prior to switching seem to be used correctly in a promotion.

**Possible Solution**  
Show the button for all promotion/discount types. There is no real reason to hide it, is there?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
