### ISSUE TITLE
Remove stored values from language / inherit from base language - especially for custom fields

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1724]
**Description**  
As custom fields are always translatable but various fields/field types seldom require translations, it would be nice to have an option to remove a stored value and inherit it through the language chain.
he problem is that once a field is stored it is tricky to remove, e.g. a boolean flag will only switch to true or false but cannot be removed. 
And for texts there is actually a difference between removing texts (empty string) for the language or inheriting it through the language chain. Also the texts fields to not show that e.g. the text is inherited from a different language (e.g. sytem language) for custom fields in contrast to e.g. the product title.

My first idea was to use the lock like with sales channel configuration fields. However, the issue here is that e.g. for products the lock is already used for variant specific values which will be an issue here.

Another solution might be to add an option to a custom field that it is not translatable which results in it always being stored in the system default language. It is not that nice as it will only work for fields that do not need to be translated at all.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
