### ISSUE TITLE
API: hex ids with uppercase letters will be suppressed 

### ISSUE THREAD

**Issue by ireznik** [shopware/platform#1730]
**Description**  
Providing hex ids with uppercase characters trigger an error in the api: FRAMEWORK__PRIMARY_KEY_NOT_PROVIDED
**Possible Solution**  
Change Regex Pattern inside of the Uuid::isValid Method to accept uppercase hex ids which are also valid
**Additional context**  
https://github.com/shopware/core/blob/0f6ac7e31b395cbc3201a47286353477a123d75d/Framework/Uuid/Uuid.php#L13

Referring to the symfony UuidValidator: https://github.com/symfony/symfony/blob/15764b42008e41b9100dfbb8f5165074046b7b65/src/Symfony/Component/Validator/Tests/Constraints/UuidValidatorTest.php#L209

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
