### ISSUE TITLE
mailto Links in RTE

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1734]
**Description**  
mailto Links in RTE seems to be converted to something like `http://foo@example.com`.
If I manually change them in the source code it works but it would be nice, if such links could be used directly from the RTE.

**Comment by AndreasA** [comment]
The same is probably also the case for `tel:` links and similar links.


Also I think custom schemes are not supported either. I mean they can be enetered but upon saving and reopening the content the links is lost which is actually a bit of an issue e.g. app uris etc.

**Comment by aragon999** [comment]
Is this issue still present in the current versions? 

I just checked and for me everything works as expected (in my case I edited a category description). The snippets work as well.

**Comment by AndreasA** [comment]
Haven't tried this in a while, probably will be able to verify next week, otherwise occupied beforehand

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
