### ISSUE TITLE
Cart errors in the storefront template do not use the parameters for translation

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1736]
**Description**  
The flashbag cart error message uses the `parameters`  array for translation texts. However, the cart error output itself does not, it only uses the `name` property/getter of the cart error. However, a cart error does not acutally require that property/getter.

**Possible Solution**  
- Adjust cart error template to pass on the parameters as is done for the flash bag. See template: https://github.com/shopware/platform/blob/trunk/src/Storefront/Resources/views/storefront/component/checkout/cart-alerts.html.twig

**Comment by mitelg** [comment]
seems to be duplicated with #1717

**Comment by AndreasA** [comment]
@mitelg This issue is more regarding cart and flashbag. 
Those are not related to the off-canvas cart. Or maybe they are (?).

But this issue is more related to e.g. if I open the cart and I change the quantity and an error is added to the cart, it will be shown twice https://github.com/shopware/platform/issues/1735 one time from the flash messages where the parameters are used and one time where only the name as parameter is used (which might not exist)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
