### ISSUE TITLE
Directories / group shopping experience layouts

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1739]
**Description**  
If one has multiple sales channels and the same shopping experiences but with different content and/or blocks and sections, one easily looses the overview in the shopping experience admin interface.

It would be nice if one could group the pages like e.g. in media where folders can be created.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
