### ISSUE TITLE
Create an order from a cart should fail if prices etc. change between showing summary and ordering (or optionally avoid recalculation)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1741]
**Description**  
- Create a rule that is active from 10:00am to 11:00am.
- Create products with advanced pricings that uses that rule.
- Add products to the cart at about 9:55am.
- Go through the checkout process, up to the summary page.
- Wait until 10:01am.
- Press order.

Now the prices will be different between the one shown at the summary page and the one the user orders.

**Possible Solution**  
- Upon cart rule loading (context resolve) remember the cart without calling cart processor (e.g. in memory).
- After recalculating the cart during the order creation, check if the newly calculated cart differs from the remembered one.
- If it does, add a cart error to the cart that blocks the order completion. This one will then be automatically shown in the Storefront and also returned to store API calls. 

Minor issue with that:
- In case this request fails due to other errors, the original cart is lost and a refresh would not have any changes but that is quite an unlikely scenario and probably means that there are other issues anyway.
- Solution for that might be to store the cart in the database upon accessing the summary page or calling the store-api with a parameter and compare against that cart instead.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
