### ISSUE TITLE
Optional Entity Selector's are not setup with the reset option.

### ISSUE THREAD

**Issue by gRoberts84** [shopware/platform#1742]
**Description**  

I'm finding a number of modules/components that use the `<sw-entity-single-select>` component have not been setup with the `resetOption` despite the field being optional before being set.

**Additional context**  

An example - I accidentally set a main category on a sales channel for a product. I am now unable to remove it unless I go into the database and remove it.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
