### ISSUE TITLE
Error while using Import/Export module with Google Cloud Storage

### ISSUE THREAD

**Issue by steven-codegasm** [shopware/platform#1747]
**Description**  
The Shopware-Export-Module throws the following warning when I use the Google Cloud Storage adapter:
`PHP Warning: stream_copy_to_stream(): supplied resource is not a valid stream resource`
The problem is, this adapter uses Guzzle to upload the file/chunk and Guzzle closes the resource. The next upload iteration/loop is not able to use this resource again.

**Possible Solution**  
A possible solution could be to add a `$this->initTempFile();` in Shopware\Core\Content\ImportExport\Processing\Writer\AbstractFileWriter.php Line 49

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
