### ISSUE TITLE
SEO URLs not replaced in email templates

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1748]
**Description**  
The MailService does not have the `renderStorefront` method available in the storefront controller and therefore no SEO url replacement happens.

**Possible Solution**  
Manually call the seo url replacer for all data segments in the mail service.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
