### ISSUE TITLE
RTE (Text editor) and other link fields allow link schemes to products etc.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1749]
**Description**  
It would be nice if I could link to a product category etc. by entering something like:
- category://<id>
- home://

etc.

Even better would be to combine this with the admin interface to select products etc. directly like requested in  https://github.com/shopware/platform/issues/767 but even something like this would be a huge improvement to now. Especially, it would still work if you ever change the route paths.

**Comment by AndreasA** [comment]
From what I see the link is also lost if such custom schemes are used, after saving the data and entering edit again.

This is also a problem for  e.g. app scheme urls, not that often needed but it should still work.

**Comment by AndreasA** [comment]
This is also the case for other link fields like e.g. the external URL for categories. It should be possible to link to e.g. a product there.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
