### ISSUE TITLE
Language switcher title attribute empty as language is non translatable

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1750]
**Description**  
Language switcher uses `language.translated.name` as title attribute but language entity is not translatable so this cannot work: 
https://github.com/shopware/platform/blob/trunk/src/Storefront/Resources/views/storefront/layout/header/actions/language-widget.html.twig#L38

Replaces the wrong issue opened by me previously: https://github.com/shopware/platform/issues/1710

**Possible Solution**  
Remove `.translated.` and use `language.name` directly.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
