### ISSUE TITLE
Elasticsearch cleanup task fails for a lot of languages due to http.max_initial_line_length

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1751]
**Description**  
If the language pack plugin is installed a lot of indices are created as one is created per language and entity and for each language two inherited languages are added (e.g. another country). Or just the language pack and the enterprise search (more default indices).

Now, if the `es:index:cleanup` is called, it will fail with the default elastic search settings as the request query is larger than `http.max_initial_line_length`.

**Possible Solution**  
Retrieve the indices not all at once but in buckets.

**Comment by AndreasA** [comment]
Might not be an issue if the index length is low enough. At least not without increasing the language count event more.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
