### ISSUE TITLE
es:create:alias - Creates a lot of unassigned shards - reaches max shards limit upon reindex

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1752]
**Description**  
If the language pack extension is installed a lot of indices are created - which is fine by itself. However, upon calling `es:create:alias` elasticsearch has about 720 shards created instead of the 180 or so beforehand. And most of them are unassigned.  The assigned shards are still 180.

The elastic search cleanup task also does not remove those unassigned shards at least in a single node cluster (local development or not too many products to require multiple nodes). 

I guess I could decrease the `number_of_replicas` in the elasticsearch configuration but as that is actually one large parameter I would first need to copy the full parameter config as that parameter cannot be merged as you just use a parameter with sub array keys instead of e.g. a Symfony configuration definition or multiple parameters but I think it would make sense to detect if the replication makes sense at all. 

Maybe add env variable settings for `number_of_shards` and `number_of_replicas`.

Now with the default settings, a second reindex is not possible anymore as it would requirer more than 1000 shards.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
