### ISSUE TITLE
GenericPageLoadedEvent not dispatched on default 404 page

### ISSUE THREAD

**Issue by runelaenen** [shopware/platform#1762]
**Description**  
In the ErrorController, the GenericPageLoadedEvent is not dispatched when a 404 page is rendered.

On line 71, in the errorPageLoader, this does happen.
https://github.com/shopware/platform/blob/trunk/src/Storefront/Controller/ErrorController.php#L71

However, this is only called when a CMS Page/Layout is set up as a custom 404 page. When using the default 404 page,
the event is never dispatched.

https://github.com/shopware/platform/blob/trunk/src/Storefront/Controller/ErrorController.php#L78-L85

**Possible solution**
Properly dispatch event, either in the controller, in the template resolver, or extract it into an ErrorPageLoader.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
