### ISSUE TITLE
Listing filter breaks when closing off-canvas via X button

### ISSUE THREAD

**Issue by gRoberts84** [shopware/platform#1768]
**Description**  

After choosing your filters within the off-canvas listing filter pop-up, if you click on the X, it reverts the URL due to off-canvas calling `history.back()` via `Iterator.iterate(closeTriggers, trigger => trigger.addEventListener(event, this.goBackInHistory.bind(this)));`.

Whilst the listing will still show the filtered items based on your selection, you are no longer able to reset the filter, nor does it correctly show the current state.

Clicking on the backdrop of the off-canvas pop-up however works fine. 

**Possible Solution**  

Confirm if `this.goBackInHistory` is needed upon closing of off-canvas elements, or if it can be toggled depending on the situation.

**Additional context**  

If you dismiss the off-canvas pop-up by clicking on the backdrop, you are able to then use the X for subsequent uses of the filter until you reload the page.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
