### ISSUE TITLE
Storefront HTTP Client and Store API client services (Javascript) - Support promises instead of only callbacks

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1778]
**Description**  
It would be nice if the HTTP client and store api client service could support promises instead of callbacks as promises have multiple advantages,

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
