### ISSUE TITLE
Quick edit in admin - Image slider - After language switch or save no images displayed until reload

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1779]
**Description**  
In the admin, if the user selects quick edit mode for shopping experiences, if the language is switched or the content is saved, the images from the image slider are gone. Upon a reload they are there again but this way the user cannot save until a reload as the slider is missing its images.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
