### ISSUE TITLE
Mobile menu ignores external URLs sometimes

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1780]
**Description**  
The mobile menu does not always use the external URL correctly. It just renders the URL for the category page instead.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
