### ISSUE TITLE
Terms and conditions checkbox in checkout - No validation error if not checked

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1781]
**Description**  
If the terms and conditions are not checked an a user tries to submit the order, then no error is displayed.

Furthermore, the terms and conditions checkbox should be just above the submit button, so that if there are errors, one sees those errors.

**Possible Solution**  
Add the form validation plugin to the form. Ensure it works with the checkbox being outside the form tag and move the checkbox to just above the submit button.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
