### ISSUE TITLE
Combine FormSubmitLoaderPlugin and FormValidation javascript plugins in storefront

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1782]
**Description**  
Currently if both are used on the same form, the loader is shown although the validation fails.

**Comment by s-diez** [comment]
I just had the same problem. My Solution would be to check if `event.defaultPrevented` is set in FormSubmitLoaderPlugin::_onFormSubmit. Would Shopware accept such a PR?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
