### ISSUE TITLE
Wrong transactionstate and wrong orderstate in frontend (account/order-history/order-item)

### ISSUE THREAD

**Issue by LinoJo** [shopware/platform#1786]
**Description**  
If the customer creats more than one transaction by intterupt while paypal payment, error etc. then will be the overview in <host>/account incorrect. All states will be related by the **last transaction**.

**Possible Solution**  
Looks like everything is fine, but the last transaction is the oldest one. There is needed the newest one!
It should be **transactions.first** instat of **transactions.last**. Nearly miss ;)

**Additional context**  
Path:  platform/src/Storefront/Resources/views/storefront/page/account/order-history/order-item.html.twig
Row: 67, 125, 278, 287

**Please fix it quick!!**

**Comment by LinoJo** [comment]
Would be greate, when PayPal supports multiple transaction in backend, too! :) Thanks a lot

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
