### ISSUE TITLE
Request transformers (and canonical redirect service) - Symfony's exception event is not triggered upon exception as outside Symfony kernel, e.g. sales channel mapping not found for automatic language redirects

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1788]
**Description**  
If the request transformer triggers an exception, e.g. sales channel mapping not found, then Symfony's exception event is not triggered which results in non nice looking error pages but default server error messages and it also does not allow one to add custom logic in that case, e.g. forward to a default specified URL or redirect to the correct language based on the browser settings.

**Possible Solution**  
Catch all exceptions in addition to the dbalexception and trigger either Symfony's exception event or a custom event that allows one to return a response etc.

Or use the `RequestEvent` to transform the request instead with a corresponding priority.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
