### ISSUE TITLE
Mail templates - A lot of bugs, cosmetic issues etc.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1791]
**Description**  
The current mail templates have a lot of issues:

- Some are not translated in German.
- The language pack plugin does not provide translations for the default mail templates
- Some use letter name salutation and a generic salutation that results in something like "Hallo Sehr geehrte Frau..." in German.
- Mail templates that use generic salutation always do so, instead of optionally using the lettername if available, e.g. newsletter registration template. This is further an issue as salutation does not seem to be joined to the data.
- Generic salutation is kind of informal with "Hallo" and "Hello" for a Shop.
- Subjects quite often wrong.
- Sometimes salesChannel.name used instead of salesChannel.translated.name
- Sometimes shopName used but with nearly all others salesChannel.name is used.
- font sizes and families sometimes hard coded in the template content block which makes it more tricky to override using header / footer templates.
- Some email templates include a sincerely ... footer but that should probably be part of the header / footer templates.
- Order confirmation mail does not have the customer comment.
- Order confirmation mail does not show phone numbers for addresses.
- etc.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
