### ISSUE TITLE
Mail service events - Please provide data like mail template name and type, template data etc.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1792]
**Description**  
The mail service has some events but very often it has limited options, e.g. missing template name and type, which makes it more tricky than necessary to e.g. add a bcc to some template types.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
