### ISSUE TITLE
Mail service - Inlince CSS (style tags) automatically - support?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1796]
**Description**  
For outlook and some programs it is best to add style attributes to nearly all elements to ensure content is displayed correctly. There are corresponding libraries that do so automatically and would be nice to have as an optional feature.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
