### ISSUE TITLE
Mail - Easy support to embed / reference resources ?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1797]
**Description**  
It would be nice to have an option to either:

- embed resources like images (e.g. logo) or even font-face (for those few clients that support it)
- and reference them from the website (media) and ensure that they are marked as refernced, so one does not accidentally delete them.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
