### ISSUE TITLE
Extend mail template / blocks

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1798]
**Description**  
Would be nice to extend mail templates the same way as storefront templates, e.g. by extending the order confirmation mail and additional stuff to it for some customers only or if it is sent to the Shop owner.

**Comment by mitelg** [comment]
Maybe this plugin will help you https://github.com/FriendsOfShopware/FroshPlatformTemplateMail

we decided to store the templates in the DB to make it easier for merchants without technical background to adjust them

**Comment by AndreasA** [comment]
I meant to extend existing database template by e.g. specifying a parent. it woudl also be helpful for editors.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
