### ISSUE TITLE
Mobile menu - External links ignored

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1799]
**Description**  
External links (corresponding category type) in the mobile menu are ignored and just render the link to the category like it is a normal category.

**Possible Solution**  
Adjust the twig template to check for category type and handle it accordingly.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
