### ISSUE TITLE
Redirect categories with external URLs to corresponding page

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1800]
**Description**  
If one knows the URL of a category that is actually an external URL category, that category can still be accessed and it then shows an empty page which really does not make any sense. It would be nice, if it would automatically redirect to the correct page instead.

Don't forget to support SEO-URL patterns there, so the domain place holder and the `#` can be used as suffix.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
