### ISSUE TITLE
Last level in mobile menu should instead show parent level and highlight current page?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1802]
**Description**  
Not 100% sure about this but the current behavior to only show the page title and a back button is kind of weird. it would probably make more sense to show the parent level here instead and highlight the current page. Not sure about the page title though, should probably still be the current page.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
