### ISSUE TITLE
Product page not showing any category as active?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1803]
**Description**  
Not sure if this requires a main category to be set but if a product is selected no category is marked as active in the menu (main, and probably also mobile).

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
