### ISSUE TITLE
Open T&C etc. in a new tab and set a page/category instead of the layout

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1804]
**Description**  
It would be nice to not just allow T&Cs etc. to be used using a modal but also allow it to open a full page. This, however, would require a category to be assigned instead of just the layout and it should be optional.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
