### ISSUE TITLE
Contact form, finish payment (upon failed payment) and probably others: No loading spinner 

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1805]
**Description**  
Contact form, finish payment (upon failed payment) and probably others do not show a loading spinner but just submit the data.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
