### ISSUE TITLE
Easier option to show full page layout during checkout

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1806]
**Description**  
A lot of templates have to be extended to show the full page layout instead of just the minimal layout during checkout. Would be nice if this could be done easier. Maybe even an option.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
