### ISSUE TITLE
Adjust classes for blocks during checkout / order more easily and probably also for other blocks (e.g. CMS)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1807]
**Description**  
If I just want to adjust the column settings during the checkout to show e.g. payment and shipping below, it is currently quite annoying as one has to copy quite a lot from the original template to just adjust the column css classes. Sure one can also override it using CSS but that is usally not a good idea for bootstrap col classes.

**Comment by AndreasA** [comment]
probably also relevant for other templates like e.g. cms blocks. just adding classes is kind of tricky especially when intending to call parent in the block.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
