### ISSUE TITLE
Address management for user is not exactly easy to use

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1808]
**Description**  
One of my friends tried to use the address management of the account and they had trouble using the address management without me first explainig it to them, like .e.g missing edit option for default addresses. Without adding a new address it looks like the default addresses cannot be changed at all.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
