### ISSUE TITLE
Failed payment - Customer comment lost

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1809]
**Description**  
After a failed payment, the user is redirected to the order form to retry or finish it with a different payment method.

however, that form does not show the previously entered customer comment, which means the customer has to re-enter it. 

Without them adding entering a comment, the previously added comment seems to still be added to the finished order but it is really confusing for the customer.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
