### ISSUE TITLE
Stopping guest session using the account menu is kind of confusing

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1810]
**Description**  
If I didn't know about this, I probably would have never checked in the account menu, if I could "log out" my current guest session. Probably not that huge an issue with the combination of auto logout upon order finished but it doesn't make any sense.

Maybe it would make more sense to instead immediately show the logout button with the text? not sure how best to do this but hiding it in the account menu seems counter intuitive.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
