### ISSUE TITLE
Mobile menu label: Show all categories - Not really fitting

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1811]
**Description**  
As the menu is actually used to also show landing pages that might not be related to products at all, calling the back button show all categories seems kind of wrong.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
