### ISSUE TITLE
Mail template test mails - Select more data

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1816]
**Description**  
As the data depends on the mail template, the data should be selectable accordingly. E.g. order confirmation should include the order, newsletter registration a news letter recipient etc. Otherwise a lot of data is missing and one has to test by creating orders to have all necessary data.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
