### ISSUE TITLE
Language inheritance for CMS block content

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1817]
**Description**  
Because I think this is rather important as it can get really annoying - especially image sliders etc. - I am reporting it here too and not just the Shopware issue tracker.

Add support for language inheritence possible in CMS blocks. Not just the blocks but content as well, e.g. only the image of an image and text block. best would be support for block content, blocks and sections.

See also: https://issues.shopware.com/issues/NEXT-14593

**Example**  
- Setup an image slider in system default language `en-GB`
- Add a text block and add text.
- Go to another language `de-DE` and translate the text.
- Go back to system default and a new image to the image slider.

Now the new image will not be shown in `de-DE` but only those that existed prior to switching languages.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
