### ISSUE TITLE
Test mail not using correct language for header / footer

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1818]
**Description**  
Header and footer in test mails seem to be rendered in system default language although a different language is selected and the template istelf is sent using that language.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by nick558234** [comment]
We’re still experiencing the same issue with the header and footer translations in other languages. Shopware continues to send the default language content instead of the translated version.

Shopware version: 6.5.8.16
