### ISSUE TITLE
Header / footer email templates - Add media / embed media option

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1819]
**Description**  
It would be nice to add images in the header/footer email templates out of the box, e.g. to use a logo which is directly embedded in the mail at a certain position in the template.

**Possible solution**
Add file field in header/footer which result in the CIDs being injected as twig variables.

the same option would be nice for the mail template itself too.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
