### ISSUE TITLE
Saving business events - Sometimes removes e-mail recipients settigs

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1824]
**Description**  
Not sure when exactly this happes but I just changed the mail template for a business event and the recipients were removed and I had to re-add them.

**Comment by AndreasA** [comment]
I was now able to reproduce this with a custom event. this is really annoying. It happens e.g. already if the sales channels are changed in the business event.

**Comment by shyim** [comment]
Is it maybe related to https://issues.shopware.com/issues/NEXT-15178 ?

**Comment by AndreasA** [comment]
Could be. Because mentioned that the recipients are lost is only shown after a refresh. and nearly any change to the template seems to delete them. And of course, if the recipients are gone, everything it won't work as expected.

**Comment by AndreasA** [comment]
Addition: I did not yet test with 6.4 but only 6.3.5.*

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
