### ISSUE TITLE
product_cross_selling_translation - Name field required in translation table - "null" not allowed (database) to fallback in language chain?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1829]
**Description**  
The table `product_cross_selling_translation` requires the name to be set and not null. This means that if a translation for the name already exists, it cannot be set to `null` to fallback in the language chain for that product cross selling.

Yes, in this case it currently is also possible to just remove the whole row as currently only the name is stored but in case additional translated fields are ever added this will be an issue.

**Possible Solution**  
Make the name field in the database nullable. DAL already supports this for non system default translations.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
