### ISSUE TITLE
`$event->getIds()` returns `null` for `CustomerEvents::CUSTOMER_WRITTEN_EVENT`

### ISSUE THREAD

**Issue by RafaelKr** [shopware/platform#1832]
I have an event subscriber listening for `CustomerEvents::CUSTOMER_WRITTEN_EVENT`.
But when calling `$event->getIds()` I get `null` back.

![image](https://user-images.githubusercontent.com/14234815/110512475-85877a00-8105-11eb-9c97-18088a56ab3e.png)

My current workaround:
```php
array_map(
  fn ($result) => $result->getPrimaryKey(),
  $event->getWriteResults()
)
```

Is this the correct place to report such issues? Or would https://github.com/shopware/platform be more appropriate? (or the forum?)

Edit: currently I'm at shopware/development tags/v6.3.5.1

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by RafaelKr** [comment]
Just for reference, this is fixed by https://github.com/shopware/core/commit/4e512c3e935b18d9d3124aff3e29e701cc8812ab#diff-748c132d3ae504c5731ced57989e1ccbf524e921aa77c01df779cebb9c85839eR100-R106
