### ISSUE TITLE
Form violations - field names not translated (e.g. customer registration)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1835]
**Description**  
The form input violations of e.g. the customer registration form use `%field% ...`. However `%field%` is not translated, so e.g. `Zipcode cannot be empty` is displayed, although in the admin the user translated zipcode with `Postalcode`. Sure, there is Javascript validation but not everything is always handled by Javascript.

**Possible Solution**  
Translate field names.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
