### ISSUE TITLE
 Form violations (e.g. registration) - Allow custom message and include all parameters

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1836]
**Description**  
Sometimes it would be nice to use a completely custom message instead of the generic like pattern does not match. In Symfony this is usually done by the `message` defined in the constraint which can be overridden per field etc. but in Shopware this is done using the codes instead and cannot be overridden without creating a custom constraint.

The simplest solution would be to use the message instead of the code or add a custom messageKey property to the constraint.

Furthermore, not all parameters are injected into the error message instead of just the field name.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
