### ISSUE TITLE
@6.4 Products with category associations need up to 20s execution time in storefront

### ISSUE THREAD

**Issue by moorl** [shopware/platform#1838]
**Description**  
I have around 5k products in my dev shop. If I associate a product to a category I have a very long execution time. If I remove the association I have <1s execution time.

The Symfony Profiler shows:

![image](https://user-images.githubusercontent.com/45460948/116933035-4b4cdb80-ac63-11eb-8f31-38d5b744cb6d.png)

But I have no idea what happens in the core here. I just can say, this bug wasn't there in the older SW version.

**Comment by shyim** [comment]
Can you post the slow query?

**Comment by moorl** [comment]
```
Time                 Id Command    Argument
# Time: 2021-05-03T21:42:05.277424Z
# User@Host: app[app] @ localhost []  Id:  1899
# Query_time: 18.478979  Lock_time: 0.000088 Rows_sent: 1  Rows_examined: 44713
use shopware;
SET timestamp=1620078125;
SELECT `category`.`id` FROM `category` LEFT JOIN `product_category` `category.products.mapping` ON `category`.`id` = `category.products.mapping`.`category_id`  AND `category`.`version_id` = `category.products.mapping`.`category_version_id` LEFT JOIN `product` `category.products` ON `category.products.mapping`.`product_id` = `category.products`.`categories`  AND `category.products`.`version_id` = `category.products.mapping`.`product_version_id` LEFT JOIN `product` `category.products.parent` ON `category.products`.`parent_id` = `category.products.parent`.`id` AND `category.products`.`version_id` = `category.products.parent`.`version_id` WHERE (`category`.`version_id` = '^O©^\ãéjKÂ¾KÙÎu,4%') AND ((`category.products`.`id` <=> '^H¬v*     JA&· £^Y¡8Â/' AND (`category`.`path` LIKE '%|d527b1cac40a4256939477cf85a5dfe2|%' OR `category`.`path` LIKE '%||%' OR `category`.`path` LIKE '%||%'))) GROUP BY `category`.`id` LIMIT 1;
```

**Comment by OliverSkroblin** [comment]
Can you please post the whole Symfony performance metrics? (you can increase the threshold, to minify the metric)

On which page is that query, product detail page or product listing?

Can you provide a script which reproduce the behavior?

**Comment by moorl** [comment]
Just put 5k products with category assignment using this trunk. I test without any plugins or themes to be 100% sure. This happens on product detail, not product listing.

**Comment by moorl** [comment]
If I remove this: 
https://github.com/shopware/platform/blob/d6c853ca3b6b167d61d70e6329f4fcface5c5245/src/Core/Content/Category/Service/CategoryBreadcrumbBuilder.php#L81

Or if I define a main category (Not sure if it still works with 5k main catrgories) it loads faster.

Have no Idea why I get a `slow query` there, I hope its not a general bug.

**Comment by moorl** [comment]
This core changes fixed it for me. Additional i have to add a `categories` association to the product criteria!

Not final but just an Idea!

```PHP
    public function getProductSeoCategory(ProductEntity $product, SalesChannelContext $context): ?CategoryEntity
    {
        if ($product->getCategoryTree() === null || \count($product->getCategoryTree()) === 0) {
            return null;
        }
        
        $category = $this->getMainCategory($product, $context);

        if ($category !== null) {
            return $category;
        }
        
        if ($product->getCategories() === null) {
            return null;
        }

        $criteria = new Criteria($product->getCategories()->getIds());
        $criteria->setLimit(1);
        $criteria->addFilter(new EqualsFilter('products.id', $product->getId()));
        $criteria->addFilter(new MultiFilter(MultiFilter::CONNECTION_OR, [
            new ContainsFilter('path', '|' . $context->getSalesChannel()->getNavigationCategoryId() . '|'),
            new ContainsFilter('path', '|' . $context->getSalesChannel()->getServiceCategoryId() . '|'),
            new ContainsFilter('path', '|' . $context->getSalesChannel()->getFooterCategoryId() . '|'),
        ]));

        $categories = $this->categoryRepository->search($criteria, $context->getContext());

        if ($categories->count() > 0) {
            return $categories->first();
        }

        return null;
    }
```

**Comment by moorl** [comment]
On a native webhosting server the problem still there - a little bit faster with 10s. Just the cache reduce the loading time if you open a product twice. Please fix it soon!

**Comment by jonashrem** [comment]
We noticed the same situation with some of our customers after switching to shopware 6.4

![grafik](https://user-images.githubusercontent.com/1112507/118247941-0b2bfb00-b4a4-11eb-8c93-7e34aa959c0d.png)
![grafik](https://user-images.githubusercontent.com/1112507/118248234-5e9e4900-b4a4-11eb-9d03-cf101daf41fb.png)

If you need any further informations, please let me know.

**Comment by shyim** [comment]
Will be fixed with next version https://issues.shopware.com/issues/NEXT-15215

**Comment by jonashrem** [comment]
@shyim Can you publish the code changes in the meantime? So it is possible to fix this before 6.4.1 is released?

**Comment by OliverSkroblin** [comment]
@jonashrem 

We have problems with the last patch version of maria db, so the pipelines are red right now and we haven't merged the fix yet. As soon as it is merged, I will link it to you.

**Comment by ansgarbecker** [comment]
Not sure where that happens but the `EqualsFilter` generates a [NULL-safe equal operator](https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_equal-to): `<=>`. Replacing the `<=>`  with a simple `=` operator tells the MySQL optimizer to use the primary key in product table, and examins only a few rows (instead of _all_ rows in product table). See the difference in the "rows" from the `EXPLAIN` output:

```sql
SELECT c.id FROM category c
LEFT JOIN product_category pc ON c.id = pc.category_id  AND c.version_id = pc.category_version_id
LEFT JOIN product p ON pc.product_id = p.categories  AND p.version_id = pc.product_version_id
LEFT JOIN product pp ON p.parent_id = pp.id AND p.version_id = pp.version_id
WHERE (c.version_id = 0x11)
	AND (
            (p.id <=> /* try = here */ 0x11 AND (
                c.path LIKE '%|123|%'
                OR c.path LIKE '%||%'
                OR c.path LIKE '%|456|%')
            )
        )
GROUP BY c.id
LIMIT 1
```

Using <=>:
| id | select_type | table | partitions | type | possible_keys | key | key_len | ref | rows | filtered | Extra | 
| ---: | --- | --- | --- | --- | --- | --- | --- | --- | ---: | ---: | --- | 
| 1 | SIMPLE | category |  | ALL | PRIMARY,auto_increment,idx.level,fk.category.media_id,fk.category.parent_id,fk.category.after_category_id,fk.category.product_stream_id,fk.category.cms_page_id |  |  |  | 1300 | 2,98 | Using where; Using temporary; Using filesort | 
| 1 | SIMPLE | pc |  | ref | fk.product_category.category_id | fk.product_category.category_id | 32 | shopware.category.id,const | 190 | 100,00 | Using where; Using index | 
| 1 | SIMPLE | p |  | ALL |  |  |  |  | 72988 | 10,00 | Using where; Using join buffer (Block Nested Loop) | 
| 1 | SIMPLE | pp |  | eq_ref | PRIMARY | PRIMARY | 32 | shopware.p.parent_id,shopware.p.version_id | 1 | 100,00 | Using index | 

Using =:
| id | select_type | table | partitions | type | possible_keys | key | key_len | ref | rows | filtered | Extra | 
| ---: | --- | --- | --- | --- | --- | --- | --- | --- | ---: | ---: | --- | 
| 1 | SIMPLE | p |  | ref | PRIMARY | PRIMARY | 16 | const | 1 | 100,00 | Using where; Using temporary; Using filesort | 
| 1 | SIMPLE | pp |  | eq_ref | PRIMARY | PRIMARY | 32 | shopware.p.parent_id,shopware.p.version_id | 1 | 100,00 | Using index | 
| 1 | SIMPLE | pc |  | ref | PRIMARY,fk.product_category.category_id | PRIMARY | 32 | shopware.p.categories,shopware.p.version_id | 2 | 10,00 | Using where; Using index | 
| 1 | SIMPLE | category |  | eq_ref | PRIMARY,auto_increment,idx.level,fk.category.media_id,fk.category.parent_id,fk.category.after_category_id,fk.category.product_stream_id,fk.category.cms_page_id | PRIMARY | 32 | shopware.pc.category_id,const | 1 | 29,76 | Using where |

**Comment by shyim** [comment]
This is fixed with 6.4.1.0

**Comment by Proxation-mh** [comment]
Still facing the issue with 6.4.1

**Comment by shyim** [comment]
same query?
