### ISSUE TITLE
Debug available data in mail template - e.g. dump - not working?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1840]
**Description**  
It seems to be kind of impossible to debug available data in a mail template by e.g. using `dump` as that doesn't seem to be rendered at all.

**Comment by shyim** [comment]
This should be not necessary when this feature is generally available
https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Resources/config/packages/shopware.yaml#L132-L135

Can you try it with `FEATURE_NEXT_12654=1` in your .env with the trunk branch

**Comment by AndreasA** [comment]
does the preview include all sub-properties of the object? if so it will help. If not I ade still have issues to find everything. I will test this later on (probably next week)

**Comment by AndreasA** [comment]
However, it won't help in case the `initial` e-mail template is setup during plugin configuration because there the admin preview is not available. Here dump would still be helpful, especially in combination with e.g. mailhog

**Comment by AndreasA** [comment]
One more possible issue regarding this, even if I see what variables are available, I still don't know which association are joined etc. so it is helpful but not the same as dump.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
