### ISSUE TITLE
Warn about Content Loss On Layout Change

### ISSUE THREAD

**Issue by akuehnis** [shopware/platform#1844]
When a user changes the layout (shopping experience) of a category then all contents are reset to shopping experience's default values. 

As there is no warning about this fact and there is no 'undo' after switching the layout, these 3 mouse clicks can lead to customer frustration and hours of additional work. 

My wish is:

- Improvement: A clear warning: All content created in the category is lost, shopping experience will be set to default values.
- Ideally: A function to undo last change(s) or to select a previous version of the layout+content

![change_layout](https://user-images.githubusercontent.com/7479604/117182947-41e48000-add7-11eb-8a2f-0e5d61c74df3.jpg)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
