### ISSUE TITLE
sw-text-field issue with idSuffix

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [shopware/platform#1845]
**Description**

I have been looking at the documentation for [sw-text-field](https://component-library.shopware.com/components/sw-text-field).

In my case I am looping `<sw-text-field>` component and would need to have unique ids. Code follows as:

```
<div v-for="answer in answers" :key="answer.id">
  <sw-text-field
    :idSuffix="answer.id"
    placeholder="Enter answer"
    v-model="answer.text"
  ></sw-text-field>
</div>
```

My output is off all input fields is:

```
...
<input type="text" name="sw-field--answer-text" id="sw-field--answer-text" placeholder="Enter answer">
...
```

I am getting DOM violation: `Found X elements with non-unique id #sw-field--answer-text`.

It looks like that `idSuffix` is not applied to `id` of input. I have also tried `idSuffix="someValue"` (with hardcoded value instead of binding variable).

**Additional context**

I am using Shopware version v6.3.5.2.

Can this issue be investigated? I would ask for some pointers if I am doing anything wrong.

And keep up the good work! Thank you in advance.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
