### ISSUE TITLE
[v6.4.0.0] Shopping experiences do not show assignment anymore

### ISSUE THREAD

**Issue by miko007** [shopware/platform#1850]
**Description**  
Since the update to Shopware version `6.4.0.0`, the visual cues in the administration about which shopping experience is already assigned *(green dot in the overview, column `Assignment` in list view is zero)* are gone. Also, they do not show a preview anymore when in *"tiled view"*.

The assignments are still there, they also work on the frontend and get listed in the detail view of any given category, but navigating through the Shopping Experiences themselves is a bit of a hassle now.

Had been tested on three different systems *(locally, development and staging)* and it seems like all of them are affected.

**Possible Solution**  
–

**Additional context**  
The issue does also occur, when we switch to the default theme, so we can pretty much rule out any custom code as the culprit.

**Comment by miko007** [comment]
the green dot in the overview seems fixed in `6.4.1.0`, the column *Assignment* when toggling to list view, still shows `0` for all *Shopping expericences* however.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
