### ISSUE TITLE
Cart error not shown in offcanvas cart upon adding items to it with APP_ENV=dev 

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1865]
**Description**  
As cart errors are only added to the flash bag with this condition:

```
  if ($request->cookies->get('sf_redirect') === null) {
            $cart = $page->getCart();
            $this->addCartErrors($cart);
            $cart->getErrors()->clear();
        }
```

The errors are not added after an item has been added to the cart, if APP_ENV=dev. also not sure why this check is here at all.
At least, if the errors have not been added to the flash bag beforehand e.g. not yet triggered in the add to cart route or the error being not marked as persistent.

**Possible Solution**  
Remove this check and do it differently, e.g. by using peek and only adding the cart flash message, if a message with the exact same content does not yet exist as the message would be the same anyway. Especially, as newly determined cart errors still have to be added. Might not the best solution but it is easy to implement and product a consitent result. Furthermore, it avoids accidentally duplicate flash messages,

**Additional context**  

Related to issue: https://github.com/shopware/platform/issues/1735

If I remember this correctly, the sf_redirect cookie is only set if the web profiler is enabled as it contains debug information for the profiler, which should not be the case in production enviornments.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
