### ISSUE TITLE
Setup database problems

### ISSUE THREAD

**Issue by pabatribick** [shopware/platform#1867]
I've tried the last 3 versions of Shopware 6, but I'M getting always Errors from the database, because all requirements are fullfilled:

Error
Received an error message.
URL: importDatabase
Message: Internal Server Error

Please try to fix this error and restart the update.
Response
{"valid":false,"errorMsg":"An exception occurred while executing 'ALTER TABLE `order` ADD `language_id` BINARY(16) AFTER `currency_id`':\n\nSQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'language_id'"}

Why is that so hard to install it and test it on an XAMPP with Windows?

**Comment by miko007** [comment]
if you get this error message at setup, it is because the database already exists, which should not be the case during setup.

**Comment by pabatribick** [comment]
This Database is empty!

**Comment by yosoyfunes** [comment]
I had the same error, it was because I was using the wrong version of MariaDB, it did not work with 10.4.19, I changed to 10.4.13 and had no problems.

https://docs.shopware.com/en/shopware-6-en/first-steps/system-requirements

![image](https://user-images.githubusercontent.com/22857813/119720556-7c729300-be40-11eb-9740-fab41fa9b3fc.png)

**Comment by shyim** [comment]
We can't fix here anything. Downgrade your Database server
