### ISSUE TITLE
User registration - No privacy policy checkbox (law)?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1869]
**Description**  
Shouldn't the user registration have a privacy policy confirm checkbox ?

**Comment by JoshuaBehrens** [comment]
This is something we regularly patch :D is it worth a PR?

**Comment by AndreasA** [comment]
I think there is actually a setting for this in recent Shopware versions (admin interface) to enable such a checkbox?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
