### ISSUE TITLE
Missing media files (not entities/database rows) trigger logout?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1870]
**Description**  
If I am logged in and an image is referenced for which the file does not exist anymore, the customer seems to be logged out (might require a separate page load).

**Comment by AndreasA** [comment]
It might just be that one of the thumbnail image formats doesn't exist, at least for the file but the entry in the database for the thumbnail exists.

**Comment by shyim** [comment]
Is this maybe already solved? In old versions sometimes the APP_URL has been used, which could differ from the current domain. This should not happen anymore

**Comment by AndreasA** [comment]
@shyim It's possible, the project is 6.3.5.2 currently and due to time limitations there currently is no time to update it.

Can you point me to the corresponding commit/fix, so I can try it?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
