### ISSUE TITLE
Shopping Experience: Translations Lost When Block Moved To Other Layout Section

### ISSUE THREAD

**Issue by akuehnis** [shopware/platform#1885]
**Description**  
When a CMS element is moved from one layout section to another, all translations are lost.

Tested and reproduced in Shopware 6.3.5.2 and 6.4.0.0

**Additional context**  
This is how to reproduce:
1. create a new shopping experience.
2. add two CMS blocks (e.g. Text) and make translations in other languages.
3. add a new layout section and add a CMS block.
4. Save your work.
5. Use the 'Navigator' and move one of the translated blocks from one section layout to another.
6. Save your work.
7. Switch the language and be shocked that all translations are gone.

A database analysis shows that cms_slot_translation really looses data. If there were two entries (english, german) for a given slot, there is only one entry left (english) after moving the block to a different layout.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
