### ISSUE TITLE
Delete unused guest customer account automatically (law - GDPR maybe?)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1903]
**Description**  
As customer guest accounts are created during checkout before the order is submitted, it is possible that guest accounts are created before an order is submitted and therefore not necessary to keep their data and the data should be deleted automatically after a certain timeframe, e.g. a day or so. This is probably also required during GDPR.

**Comment by shyim** [comment]
The time should be configureable

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
