### ISSUE TITLE
Customer address table does not keep track of customer data correctly

### ISSUE THREAD

**Issue by bpeschlaudert** [shopware/platform#1913]
**Description**  
Customer address table does not keep track of customer data correctly.

**Additional context**  
[This clip](https://streamable.com/zbinj7)

**Comment by paweljar** [comment]
@bpeschlaudert Are you using SwagB2bPlatform plugin as well?

**Comment by bpeschlaudert** [comment]
> @bpeschlaudert Are you using SwagB2bPlatform plugin as well?

No, vanilla Shopware

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
