### ISSUE TITLE
Selection between company and customer account not possible in administration

### ISSUE THREAD

**Issue by bpeschlaudert** [shopware/platform#1914]
**Description**  
After enabling `Show selection between company and customer account` in the administration, the selection should also be possible when creating a customer via the administration, which is not the case.

**Additional context**  
Visit `/admin#/sw/customer/create` and try it yourself!

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
