### ISSUE TITLE
Add the $guestCart to the CartMergedEvent

### ISSUE THREAD

**Issue by PheysX** [shopware/platform#1923]
**Description**
You are losing your extensions in the mergeCart function.
https://github.com/shopware/platform/blob/fb594702d524bfc8e297336ce7392480c975d0ef/src/Core/System/SalesChannel/Context/SalesChannelContextRestorer.php#L105

**Possible  Solution**
Add the old cart into the event to get your information over a subscriber.

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/platform/commit/8a15c2911312113a077268b2fd30500d9712a5b7

**Comment by dafen** [comment]
@shyim I really appreciate this change, this opens a lot of possibilities to finally keep the reference of an api cart after it was checked out over the storefront with a login.  

But I think there was a small mistake: the previous cart is always just a clone of the customer cart and not the guest cart as I would expect it:
https://github.com/shopware/platform/blob/trunk/src/Core/System/SalesChannel/Context/SalesChannelContextRestorer.php#L107-L113.

$customerCart and $customerCartClone are identical upon dispatch. So getting `$event->getCart` or `$event->getPreviousCart` will result in the same cart and thus the same token and no information is added by this.


**Possible Solution**
Pass $guestCart as the third parameter to the new `CartMergedEvent` instead of §customerCartClone. 

https://github.com/shopware/platform/blob/trunk/src/Core/System/SalesChannel/Context/SalesChannelContextRestorer.php#L113
