### ISSUE TITLE
Theme: Bootstrap variables location wrong according to current documentation

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1933]
**Description**  
According to current documentation of bootstrap (for 4.6 - I know you still use 4.3 but from what I can gather this should still apply and also you should actually upgrade):
https://getbootstrap.com/docs/4.6/getting-started/theming/#variable-defaults

The location for variables is not BEFORE bootstrap but after 3 of the bootstrap files are included which makes sense as this way one has access to mixins etc. and can do this https://getbootstrap.com/docs/4.6/getting-started/theming/#remove-from-map

However, with the current theme configuration such a scenario is not possible as there is no way to import files in the middle of a theme or bootstrap.

**Possible Solution**  

- Improve theme inheritance chain to optionally allow includes of specific files and not just whole themes and refactor storefront, so one can include those three bootstrap files, the rest of bootstrap and storefront stuff. This way the alias for `@StorefrontBootstrap` would also be unnecessary.
- Optionally and probably easier to implement: Add additional Storefront aliases for this like the StorefrontBootstrap alias. 
    - However, if you go with this route, you should add an option to register such aliases through the theme.json instead of doing it hardcoded in the PHP code, so other themes can use it, which is especially necessary for theme multiple theme inheritance.

issue tracker issue: https://issues.shopware.com/issues/NEXT-15844

**Comment by tobiasberge** [comment]
Hi @AndreasA,

thanks for bringing this up.

At the time we implemented the variable overrides in the theme.json it was documented differently by Bootstrap for the version 4.3: https://getbootstrap.com/docs/4.3/getting-started/theming/#variable-defaults

If I understand you correctly you would like to have the possibility to import more specific parts from Bootstrap (e.g. the grid) in your desired order rather then Bootstrap as a whole.

When it comes to your suggestion regarding additional aliases maybe an optional alias for the Storefront's resource directory would be an option. That way individual files could be accessible:

```json
"style": [
  "@StorefrontDir/app/storefront/vendor/bootstrap/scss/functions",
  "app/storefront/src/scss/base.scss",
  "@StorefrontDir/app/storefront/vendor/bootstrap/scss/root",
  "@StorefrontDir/app/storefront/vendor/bootstrap/scss/reboot"
],
```
What do you think of this idea? Or did you have something different in mind?

However I do think on the other hand that it made sense to import the complete Bootstrap package by default because otherwise we would have to maintain the imports of all bootstrap SCSS components manually. But since the 4.6 documentation suggests splitting the parts up when overriding variables we would have to come up with some kind of separated solution anyway if we would do an update to 4.6.

Right now the only solution I can think of for completely customized Bootstrap imports is to avoid the core `@Storefront` alias in the theme.json and only import your own theme's SCSS files. From there the Bootstrap files would have to be imported manually from vendor/node_modules (like in the BS documentation). Depending on the setup the path will look funky. Alternatively bootstrap could be installed as an npm package inside the own theme plugin to avoid importing from the core.

```json
"style": [
  "app/storefront/src/scss/base.scss",
],
```

```scss
// Theme "base.scss"
@import "../../../../../../../../../vendor/shopware/platform/src/Storefront/Resources/app/storefront/vendor/bootstrap/scss/functions";
@import "../../../../../../../../../vendor/shopware/platform/src/Storefront/Resources/app/storefront/vendor/bootstrap/scss/variables";
@import "../../../../../../../../../vendor/shopware/platform/src/Storefront/Resources/app/storefront/vendor/bootstrap/scss/mixins";
@import "../../../../../../../../../vendor/shopware/platform/src/Storefront/Resources/app/storefront/vendor/bootstrap/scss/grid";

// Your custom SCSS
```

Best regards
Tobias

**Comment by AndreasA** [comment]
@tobiasberge at least with a bootstrap update e.g. 5.x it will be necessary.

And it doesn't have to be file specific but I think this would give the best dynamic resolutions.

Regarding the import `../` the problem is that might fail depending on where the plugins are placed, e.g. `custom/plugins` or if one uses the vendor folder `vendor/..` due to composer install. So things like this need to be avoided

But if every plugin would have a dir alias this would work as long as the plugin does not move the files around. Not sure about the best solution but definitely something that has to be addressed with newer boostrap versions and in general is a good idea.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
