### ISSUE TITLE
ICU translation message format and yaml syntax for translations

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1936]
**Description**  
The recommended way by Symfony for translations is the ICU format. It has a lot of more options than the default, also regarding pluralization.

See: https://symfony.com/doc/current/translation.html#message-format
and: https://symfony.com/doc/current/translation/message_format.html

There they only document the ICU format for pluralization now, so it is likely that in the future support for the old format might be removed altogether.

It would be nice if this format is supported. However, this format is not so nice to maintain in JSON, so it would be nice if yaml files are also supported which should be really easy with Symfony as Symfony translator supports multiple formats by default and has all the necessary file loaders.

Issuetracker issue: https://issues.shopware.com/issues/NEXT-15840

**Comment by OliverSkroblin** [comment]
Hey @AndreasA 

as you may have noticed, we are currently only doing a very rough screening of the GitHub issues. We are mainly using our own issue tracker https://issues.shopware.com/

We are planning to merge the GitHub issues with our issue tracker, but this is an ongoing process and will still take some time.

The fastest way to get a fix into Shopware would be creating a pull request. wink Find more about that here.
Additionally, if this is really important for you, I would recommend to create a ticket on our issue tracker and link to this issue in the text.

Sorry for the inconvenience, but unfortunately this is the current status, we also have to deal with. frowning_face I assure you, that we are also not happy with it.

I know this actually does not really help, but this is our current situation :slightly_smiling_face: 

Best regards from Schöppingen
Oliver Skroblin

**Comment by AndreasA** [comment]
@OliverSkroblin I now created issue tracker issues for the newest issues I created but I am definitely not going to convert all old ones too 😄

**Comment by AndreasA** [comment]
@OliverSkroblin Isn't it possible to disable the creation of new tickets at Github but keep the existing ones? And add a link to the issue tracker instead? 

E.g. on create issue, there is only one type, that links to the issue tracker and has some information like you already have for `Report a security vulnerability`? 

However, I personally prefer the Github issue tracker because it has better integration with PRs, code etc.

Also personally I prefer the UI of the Github issue tracker, especially for comments where your layout removes a lot of width from the comment just because of the name and date but I understand that you want to have all your issues at one place.

There is also no edit option to e.g. fix typos or delete option and in general the editor is not so nice to use.

**Comment by OliverSkroblin** [comment]
I can only agree with you, I personally find the Github UI better too, but it's not plannable for us if we have X places where tickets can be posted. 

How exactly we will deal with Github issues in the future I can't tell you, that's all in clarification at the moment. Unfortunately that is the current state. 

I just wanted to point it out to you, because I always get a notice when something happens here on Github and I saw that you already spent a lot of time here in the issues :wink:

**Comment by AndreasA** [comment]
@OliverSkroblin Thanks for letting me know, I will create new tickets in the Shopware issue tracker now. And I totally understand that using multiple issue trackers is not really feasible 😄

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
