### ISSUE TITLE
OrderTransactionStateHandler.php

### ISSUE THREAD

**Issue by lxregistry** [shopware/platform#1939]
why is so difficulty to add one more state 'authorize' to this file OrderTransactionStateHandler.php

could anybody do this, just copy paste status process in authorize

**Description**  

**Example**

**Comment by lxregistry** [comment]
for Order delivery state maybe is also a good idea to have state delivered.
you have only shipped but not delivered.
a package could be shipped but lost on the way, not delivered/received

the ship date and delivery date are different

for me shipped = package sent
delivered = package received

**Comment by lxregistry** [comment]
Is there any chance to have one more state: STATE_DELIVERED and STATE_PARTIALLY_DELIVERED?

`<?php declare(strict_types=1);

namespace Shopware\Core\Checkout\Order\Aggregate\OrderDelivery;

final class OrderDeliveryStates
{
    public const STATE_MACHINE = 'order_delivery.state';
    public const STATE_OPEN = 'open';
    public const STATE_PARTIALLY_SHIPPED = 'shipped_partially';
    public const STATE_SHIPPED = 'shipped';
    public const STATE_PARTIALLY_DELIVERED = 'delivered_partially';
    public const STATE_DELIVERED = 'delivered';
    public const STATE_PARTIALLY_RETURNED = 'returned_partially';
    public const STATE_RETURNED = 'returned';    
    public const STATE_CANCELLED = 'cancelled';
}`

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
