### ISSUE TITLE
Bug in Cusomer edit custom_fields in the administration

### ISSUE THREAD

**Issue by wexollm** [shopware/platform#1940]
:bug: 
**Description**  
When editing a customer in the administration the disabled flag is not removed from datepicker input used as custom_field. It seems this is an issue only for the datepicker.

If you switch between the tabs, Addresses or Orders and then you go back to Genaral the disabled flag from the custom_field is removed. Is vice-versa when the edit-mode is disabled.

Please see the attached video that describes the bug in detail.

**Possible Solution**  

**Additional context**  
VIdeo of the bug 
https://drive.google.com/file/d/1tqKdEEjXgIoOjDiuaV6-Jn6g8ZCYKYGX/view

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
