### ISSUE TITLE
Displaying the appropriate variant attribute when the client filters the list 

### ISSUE THREAD

**Issue by axzx** [shopware/platform#1946]
### Please describe the feature you would like to see implemented.

I have a product with the size attribute (XS, S, Mm L, XL). I created variants based on this attribute.

I can set the main variant on the list to be the size M.

The customer enters the product list and searches for size S.
Could it be possible to immediately display a product with this attribute?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
