### ISSUE TITLE
Displaying available sizes in the list 

### ISSUE THREAD

**Issue by axzx** [shopware/platform#1947]
### Please describe the feature you would like to see implemented.

I have similar settings as in #1946.
Currently, the product list shows one size next to the product.
Can it be done so that all available sizes are displayed?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
