### ISSUE TITLE
Dynamic Product Group: Multiple properties AND filter

### ISSUE THREAD

**Issue by runelaenen** [shopware/platform#1977]
### PHP Version

7.4

### Shopware Version

6.4.1.2

### Expected behaviour

When adding following rules, I expect to get all products that have both 'Wheat' as '5 mm' in their properties. (I know for sure that there are products that have both property options)

![Screenshot 2021-07-26 at 13 14 33](https://user-images.githubusercontent.com/3930922/126980191-ee9e261e-af19-45f2-b44e-78e2061f5dd6.png)

### Actual behaviour

It returns no products.

![Screenshot 2021-07-26 at 13 14 56](https://user-images.githubusercontent.com/3930922/126980234-f3bab65f-d1c4-4937-bbf1-2576c1a4f1de.png)

Results with just 1 'property' line. As you can see, the test product is returned both times. But not when the rules are combined...
![Screenshot 2021-07-26 at 13 15 09](https://user-images.githubusercontent.com/3930922/126980260-2492a990-fce6-4b38-96d6-6f65592ce4c2.png)
![Screenshot 2021-07-26 at 13 15 35](https://user-images.githubusercontent.com/3930922/126980293-f5f19008-c499-4389-80b5-af9cc466cc62.png)

### How to reproduce

Recreate the rules, test the return of the preview search.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
