### ISSUE TITLE
Add an option to set the default language via CLI

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2009]
### Please describe the feature you would like to see implemented.

I need an option to set shopware's default language to something different than english (for example german) from the CLI.

Therefore I suggest to have an option, either a standalone console command or a flag for specific commands (e. g. system:install) to set the language.

**Comment by katzefudder** [comment]
You can find that special feature in their backlog, unfortunately with no additional information added.
https://issues.shopware.com/issues/NEXT-7241

There's also an open PR on the production template:
https://github.com/shopware/production/pull/24

**Comment by keulinho** [comment]
Since v6.4.6.0 you have the option to configure a shop from the CLI with the `shop-locale` or the `shop-currency` with the Iso-code of the locale or currency that should be used as the system default.

Additionally we've added a `system:configure-shop` command, that can be used after the initial setup was completed, but beware that changing system defaults after the fact may be dangerous, for all existing translations and prices in the system.

The feature was added with commit: https://github.com/shopware/platform/commit/e6456e8f5bdf91dd4f0fdc14310c42129c0a87f9
