### ISSUE TITLE
CMS Page struggle in Admin if to many Associated Categories

### ISSUE THREAD

**Issue by moorl** [shopware/platform#2016]
### PHP Version

7.4

### Shopware Version

6.4

### Expected behaviour

-

### Actual behaviour

The CMS Page Designer don't load if to many Categories are assigned. My Case is special with ~25k Categories and it's not so important. Just want to keep it in Mind.

### How to reproduce

-

**Comment by JoshuaBehrens** [comment]
Related https://github.com/shopware/platform/pull/1508

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
