### ISSUE TITLE
Swiss francs can not be removed

### ISSUE THREAD

**Issue by AlterWeb** [shopware/platform#2047]
### PHP Version

7.4

### Shopware Version

6.4.3.1

### Expected behaviour

Swiss francs will be removed after going to Settings -> Currencies and clicking on the delete option from the "Swiss francs" line

### Actual behaviour

Nothing changes

### How to reproduce

Fresh install of Shopware 6.4.3.1, go to Settings -> Currencies and clicking on the delete option from the "Swiss francs" line.

**Comment by shyim** [comment]
Do you have any error in network tab?

**Comment by ChrisH861** [comment]
I have the same issue, I'm on Shopware version 6.4.6.0
here's the error it produces in the log:
[https://gist.github.com/ChrisH861/88a3824c5d27bc5e4fe0120486e86315](https://gist.github.com/ChrisH861/88a3824c5d27bc5e4fe0120486e86315)

**Comment by keulinho** [comment]
The posted error indicates that in the shopware markets configuration that currency is still used. Probably you need to remove Swiss Francs in shopware markets first and then delete the currency.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
