### ISSUE TITLE
Product slider on Mobile

### ISSUE THREAD

**Issue by eliawk** [shopware/platform#2053]
### PHP Version

7.4

### Shopware Version

6.4.1.1

### Expected behaviour

The slider on mobile should have correct spacing 

### Actual behaviour

There is a class
```
.gallery-slider-row.is-loading {
    height: 430px;
    overflow: hidden;
}
```
which is not removed from the slider onInit so I get a big white space at the end of the slider
![Uploading Schermata 2021-09-06 alle 10.46.31.png…]()

### How to reproduce

Open the product page on mobile

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
