### ISSUE TITLE
Cant import SCSS from node_modules

### ISSUE THREAD

**Issue by sawden** [shopware/platform#2062]
### PHP Version

7.4.22

### Shopware Version

6.4.4.0

### Expected behaviour

Scss files from the node_modules are imported correctly in the final bundle.

### Actual behaviour

Scss files from the node_modules are not correctly bundled in the storefront.
The watch task does not have this problem but when the plugin is built, the imports are no longer correct.

Bug on Shopware Issuetracker for Details:
https://issues.shopware.com/issues/NEXT-14098

Forum entry that I found:
https://forum.shopware.com/t/thirdparty-owl-carousel-einbinden/85773/2

### How to reproduce
Described in the linked forum entry and the issue tracker Bug

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
