### ISSUE TITLE
the meaning of Basic information - Shop name - cleaning proposal with the name of the store 

### ISSUE THREAD

**Issue by axzx** [shopware/platform#2068]
### Please describe the feature you would like to see implemented.

We have the name of the store in the main category, in the channel name and in basic information -> shop name.

In basic information -> shop name, this name cannot be translated.
This is a big problem.
Is it not possible to standardize and display the name obtained from the channel everywhere?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
