### ISSUE TITLE
Product extensions cannot be used in CMS data mapping

### ISSUE THREAD

**Issue by macster84** [shopware/platform#2105]
### PHP Version

7.4.23

### Shopware Version

6.4.4.1

### Expected behaviour

- Call to http://localhost/api/_info/open-api-schema.json should list product extension associations and custom entities
- Custom entity values referenced via associations from product can be selected in the "Data Mapping" dropdown box of the  Shopping Experiences page

### Actual behaviour

I have a custom entity that is referenced by the product via a product extension.
I want to use the value of one of my entity's attributes in a CMS text block via the Shopping Experiences "_Data Mapping_" dropdown box.
Unfortunately my extension "product.myGreatEntity" is not listed there.

The root cause seems to be that a GET on http://localhost/api/_info/open-api-schema.json does not even return the extension. The information from this GET is indirectly used by _cms.service.js_.
There is code in the responsible class _OpenApiDefinitionSchemaBuilder_ for this GET request that is considering extensions and assembling an in-memory structure. But the structure returned by _#getSchemaByDefinition_ seems wrong with respect to what the calling class _OpenApi3Generator_ is expecting.

I tried to hack-fix the returned structure for extensions in _OpenApiDefinitionSchemaBuilder_ but unfortunately could not make it work with reasonable effort. Trying to understand the logic for extensions I looked at the test classes _OpenApiDefinitionSchemaBuilderTest_ and _OpenApi3GeneratorTest_ but could not find any related test there either.

### How to reproduce

- Create a custom entity
- Create a product extension with an association to that entity
- Call http://localhost/api/_info/open-api-schema.json and see the extensions not being returned
- Try to use the entity in a "Data Mapping" in the Shopping Experiences CMS editor

**Comment by ulbiopro** [comment]
I can't imagine this doesn't bother anyone? So I digged through the code and found the following:



https://github.com/shopware/platform/blob/fbfdcbe6acd95cbd5b535a558780e35c3a1f7aa0/src/Core/Framework/Api/ApiDefinition/Generator/OpenApi3Generator.php#L149

`$schema->allOf[1]` has a property "properties" which includes "extensions".
After converting it to json, the key value pair "extensions" is lost.

I don't know why, but this seems to be part of the issue.

I was a bit confused, because relationships are working flawlessly...
So what I did was the follwing:

I added extensions in the same way as relationships, as property. It will be available in the http://localhost/api/_info/open-api-schema.json after that.


https://github.com/shopware/platform/blob/fbfdcbe6acd95cbd5b535a558780e35c3a1f7aa0/src/Core/Framework/Api/ApiDefinition/Generator/OpenApi/OpenApiDefinitionSchemaBuilder.php#L160-L164

```php
165            if (\count($extensionAttributes)) {
166                $schema[$schemaName . 'JsonApi']->allOf[1]->properties[] = new Property([
167                    'property' => 'extensions',
168                    'properties' => $extensionAttributes,
169                ]);
170            }
```
so the become available in https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Api/ApiDefinition/Generator/OpenApi3Generator.php

But then it still won't be found for *Data Mapping*, because only the first layer of an entity seems to be considered as available data.
  
  
To add them in the correct layer, i merged extensions to the schema in the same way the relationships where merged...
https://github.com/shopware/platform/blob/fbfdcbe6acd95cbd5b535a558780e35c3a1f7aa0/src/Core/Framework/Api/ApiDefinition/Generator/OpenApi3Generator.php#L173-L182



We can simply add an array_merge after line 210:

https://github.com/shopware/platform/blob/fbfdcbe6acd95cbd5b535a558780e35c3a1f7aa0/src/Core/Framework/Api/ApiDefinition/Generator/OpenApi3Generator.php#L210

```php
211     $properties = array_merge($properties, $extensions);
```


After that extensions become available for DataMapping in Shopping Experiences.

And Maybe this helps to solve the issue. (:

Maybe I can decorate sth for now, but not sure. :-/

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
