### ISSUE TITLE
OrderStateTransactionStateHandler can't handle reminded

### ISSUE THREAD

**Issue by PheysX** [shopware/platform#2116]
### PHP Version

7.4

### Shopware Version

6.4.5.1

### Expected behaviour

The order is marked as `paid` without error 

### Actual behaviour

```
$this->orderTransactionStateHandler->paid($transactionId, $context);
```

This is throwing an error, when the current transaction state is `reminded` because it want `pay` and not `paid`

I also didn't find a constant for `pay`. Just for `paid`. Maybe its a spelling mistake?

### How to reproduce

1. Set the order to reminded
2. Try to use the orderTransactionStateHandler paid method
3. `SYSTEM__ILLEGAL_STATE_TRANSITION` Error

Possible transitions:
* authorize
* cancel
* do_pay
* pay
* pay_partially
* process_unconfirmed
* reopen

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
