### ISSUE TITLE
Variations cannot be generated

### ISSUE THREAD

**Issue by MrSnoozles** [shopware/platform#2145]
### PHP Version

7.4

### Shopware Version

6.4.5.1

### Expected behaviour

Product variations are created from selected attributes.

### Actual behaviour

A JavaScript error occurs.

![variations-bug](https://user-images.githubusercontent.com/17496592/138075333-cc3d7680-6333-4d72-898b-380cadd9fdd6.gif)

### How to reproduce

1.  select some product properties to create the variation
2. click on "generate variations"
3. wait forever

**Comment by MrSnoozles** [comment]
The exclusion tab does not work either.

![variations-bug2](https://user-images.githubusercontent.com/17496592/138079192-50d0535a-ab5f-4ba0-9acc-b7e4a6499105.gif)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
