### ISSUE TITLE
Create subcategory on Safari

### ISSUE THREAD

**Issue by Magnusvb** [shopware/platform#2146]
### PHP Version

7.4.21

### Shopware Version

6.4.99 Stable

### Expected behaviour

On Safari (v. 15) creating a subcategory (of Home) using the contextual menu, should create a new, inactive subcategory.

### Actual behaviour

The textfield for the name of the subcategory opens, but when clicking the blue checkmark it disappears and no new category are created.

On Shopware version 6.4.0.0 RC 1 it works correctly  - the new subcategory are created. Using Firefox development edition it works correctly in version 6.4.99 Stable

### How to reproduce

With Safari, go to Catalog > Categories.
Click the contextual menu for the Home top level menu.
Set a new for the category
Click the blue checkmark

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
