### ISSUE TITLE
Customer export not generating entries 

### ISSUE THREAD

**Issue by MrSnoozles** [shopware/platform#2147]
### PHP Version

7.4

### Shopware Version

6.4.5.1

### Expected behaviour

When exporting the default profile for customers, I should get a CSV with all customers in the shop.

### Actual behaviour

The export never finishes and the number of results stays at 0.

![grafik](https://user-images.githubusercontent.com/17496592/138077908-ba8bb4d7-5f20-4efa-b554-b37e5639deb2.png)

### How to reproduce

1. Go to settings > import/export
2. click the export tab
3. choose "standard profile customer" for export and start the export
4. wait forever

**Comment by wrongspot** [comment]
hey @MrSnoozles is your message queue running? since shopware 6.4.5.0 (https://github.com/shopware/platform/blob/trunk/changelog/release-6-4-5-0/2021-08-24-import-and-export-in-message-queue.md) import/export is running via message queue.

**Comment by TimWuyts** [comment]
We're experiencing the same issue, both on production and local environments.
The message queue is also running on both instances.

When looking into the network tab, all requests are executed correctly (prepare, process, import-export-log).
Issue is occurring using all profiles & entity types (standard & custom defined ones), that have been working on previous Shopware versions.

**Comment by wrongspot** [comment]
I can`t confirm that. With Shopware 6.4.5.0 we are able to export Standard Profile "Default Customer".  Export right now.
![Bildschirmfoto 2021-10-27 um 11 27 58](https://user-images.githubusercontent.com/907458/139039213-4c8d0294-afd3-4102-96b8-0bb5db25da00.png)

**Comment by TimWuyts** [comment]
We also have a custom export function that hooks into the default import/export functionality from Shopware, which is also no longer working now. This custom function throws a 500 server error during the process request.

![Schermafbeelding 2021-10-27 om 12 51 40](https://user-images.githubusercontent.com/1556182/139052849-faedb6c2-9d37-4df7-b714-7d4cf81f548f.png)

I'm assuming the FieldSerializer is having issues processing a certain type of (custom) fields, which is causing the reported issue in some specific cases then?

**Comment by TimWuyts** [comment]
In our case the export is broken due to the following extension fields on the Product entity.

```
$collection->add(
    (new StringField('labels', 'labels'))->addFlags(new Runtime())
);

$collection->add(
    (new OneToOneAssociationField('productInfo', 'id', 'product_id', ProductInfoDefinition::class, false))->addFlags(new Inherited(), new ApiAware(), new CascadeDelete())
);
```

By adding a `new Computed()` flag to the "labels" field, the FieldSerializer will skip this value during export. It was failing since some "labels" field entries where empty ArrayEntity instances that could not be converted to a string.

However, I'm still not able to figure out what is wrong with the "productInfo" association. We have a similar OneToOneAssociation that is working during export, however the only difference is that it doesn't have any translated fields. Here you find the fields for the "broken" product extension.

```
return new FieldCollection([
    (new IdField('id', 'id'))->addFlags(new ApiAware(), new Required(), new PrimaryKey()),
    (new FkField('product_id', 'productId', ProductDefinition::class))->addFlags(new ApiAware()),

    (new StringField('product_number_legacy', 'legacyProductNumber'))->addFlags(new ApiAware()),
    (new TranslatedField('showUsage'))->addFlags(new ApiAware()),
    (new TranslatedField('usage'))->addFlags(new ApiAware()),
    (new TranslatedField('showEco'))->addFlags(new ApiAware()),
    (new TranslatedField('eco'))->addFlags(new ApiAware()),
    (new TranslatedField('showAdditional'))->addFlags(new ApiAware()),
    (new TranslatedField('additional'))->addFlags(new ApiAware()),

    (new TranslationsAssociationField(ProductInfoTranslationDefinition::class, 'dumortier_product_info_id'))->addFlags(new ApiAware()),
    (new OneToOneAssociationField('product', 'product_id', 'id', ProductDefinition::class, false))->addFlags(new ApiAware())
]);
```

```
return new FieldCollection([
    (new BoolField('show_usage', 'showUsage'))->addFlags(new ApiAware()),
    (new LongTextField('usage', 'usage'))->addFlags(new ApiAware(), new AllowHtml()),
    (new BoolField('show_eco', 'showEco'))->addFlags(new ApiAware()),
    (new LongTextField('eco', 'eco'))->addFlags(new ApiAware(), new AllowHtml()),
    (new BoolField('show_additional', 'showAdditional'))->addFlags(new ApiAware()),
    (new LongTextField('additional', 'additional'))->addFlags(new ApiAware(), new AllowHtml()),
]);
```

Is there anything wrong/missing in the above definitions?

**Comment by TimWuyts** [comment]
Our issues are related to the following changes made by @MalteJanz :
https://github.com/shopware/platform/blob/trunk/changelog/release-6-4-5-0/2021-08-30-fix-extension-column-export.md

When the following lines are commented in EntitySerializer our export (using a user-defined profile, including entity extension with translated fields) is working again. FYI: we did write some custom code using the ImportExportBeforeExportRecordEvent in order to map the fields.

```
if ($key === 'extensions') {
    foreach ($value as $extensionKey => $extensionValue) {
        if (isset($extensionFields[$extensionKey])) {
            $serializer = $this->serializerRegistry->getFieldSerializer($extensionFields[$extensionKey]);
            yield from $serializer->serialize($config, $extensionFields[$extensionKey], $extensionValue);
        }
    }

    continue;
}
```

To conclude: it would be good to have those changes in place, so we can drop our custom code for the entity extension mapping. But with the current solution in place, our translated fields are dropped from the export & the export is not processing once there is an entity extension (with inheritance flag) using translated fields.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
