### ISSUE TITLE
Allow array parameter in sw_include 

### ISSUE THREAD

**Issue by Gugiman** [shopware/platform#2148]
### Please describe the feature you would like to see implemented.

In twig documentation is mentioned that you can pass an array of templates to include function.
It then searches for the first existing template and includes it. 
https://twig.symfony.com/doc/3.x/functions/include.html

> You can also provide a list of templates that are checked for existence before inclusion. The first template that exists will be rendered:
> {{ include(['page_detailed.html', 'page.html']) }}

This could be used as some kind of else statement or fallback when using dynamic template including.

**Example:**

{% sw_include [
   '@PLUGIN/storefront/sometypes/item_' ~ type ~ '.html.twig', 
   '@PLUGIN/storefront/sometypes/item_unknown_type.html.twig'
] %}

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
