### ISSUE TITLE
Invoices are not downloadable

### ISSUE THREAD

**Issue by Konzeptphase** [shopware/platform#2164]
### PHP Version

7.4.x

### Shopware Version

6.4.4.1

### Expected behaviour

Allow customer to download invoices in their "account" area.
First: document types has to be configured to display in "account area" (displayInCustomerAccount = true)
Second: the invoice has to be sent or marked as sent.
Third: the customer will see a button to download the invoice or a document.

### Actual behaviour

All steps are done, but there are no documents in the customer area.

### How to reproduce

The bug is inside "vendor/shopware/core/Checkout/Order/SalesChannel/OrderRoute.php"
Remove the "->addFilter(new EqualsFilter('config.displayInCustomerAccount', 'true'))" line on the load() method.
All invoices which are "sent" are now visible and the configuration is correct.

**Comment by DMX4ALLGmbH** [comment]
The bug is inside "vendor/shopware/core/Checkout/Order/SalesChannel/OrderRoute.php"
Remove the "->addFilter(new EqualsFilter('config.displayInCustomerAccount', 'true'))" line on the load() method.
All invoices which are "sent" are now visible and the configuration is correct.
what is  load() method. a sample please

**Comment by DMX4ALLGmbH** [comment]
**### what is load() method. a sample please**

**Comment by DMX4ALLGmbH** [comment]
https://www.e-recht24.de/news/ecommerce/13369-die-wirtschafts-id-kommt-was-das-fuer-ihr-impressum-bedeutet.html
