### ISSUE TITLE
Backend - Ability to Edit Product Number and other fields in product grid view

### ISSUE THREAD

**Issue by neoneddy** [shopware/platform#2167]
### Please describe the feature you would like to see implemented.

When double clicking a row in the products grid view editor, it would be nice to be able to edit other fields such as product number.  In my use case, we're loading content from an older system and the client would like to hand update them.  Going into each product will be time consuming.

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/819083/140105291-6381204c-9234-4814-9cd2-5640b0d5efe3.png">

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
