### ISSUE TITLE
EntitySearchResultLoadedEvent: Not triggered if e.g. RepositorySearchDetector::isSearchRequired is false (also other scenarios)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2180]
### PHP Version

7.4

### Shopware Version

6.4.6.0

### Expected behaviour

The event EntitySearchResultLoadedEvent is not triggered for an entity in case the `new EntitySearchResult` is created because no search is required or similar.

Another scenario is in case no entities are found but even then it should still be triggered due to possible aggregations.

However, that is the only event that contains the entities and aggregations so it should still be triggered. Or if not a corresponding additional event should be created.

See:
https://github.com/shopware/platform/blob/v6.4.6.0/src/Core/Framework/DataAbstractionLayer/EntityRepository.php#L117
and
https://github.com/shopware/platform/blob/v6.4.6.0/src/Core/Framework/DataAbstractionLayer/EntityRepository.php#L125

Furthermore, the states and search extension is also not loaded in such a scenario.

### Actual behaviour

Event is not always triggered, even if I would expect it to be triggered.

### How to reproduce

- Do a search with a criteria that does not require a search - I think a criteria wich just IDs is such a criteria.
- Add event subscriber for search result loaded event for the entity and add a breakpoint there.
- Do a search.
- The breakpoint is never reached.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
