### ISSUE TITLE
I can not edit an order with an variant as there is an error "The following items are associated to products that have been deleted:"

### ISSUE THREAD

**Issue by azngeek** [shopware/platform#2181]
### PHP Version

 7.4.15

### Shopware Version

6.4.5.1

### Expected behaviour

I should be able to edit an order with a variant.

### Actual behaviour

I have an order with a variant. If i try to edit the order, this is the error i get. If i continue then the variant will be transformed to a custom product.

![image](https://user-images.githubusercontent.com/213429/141328712-851ec034-b546-48ba-9599-35547223a7a2.png)

### How to reproduce

Edit an order with a variant.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
