### ISSUE TITLE
[admin] add column customer status to customer overview

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2189]
### Please describe the feature you would like to see implemented.

I want to have an option to show the customer status (active / inactive) column in the customer overview table.

Additionally it would be great to have an additional filter to show just active or inactive customers.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
