### ISSUE TITLE
Enrich additional register form attribute (or Twig block)

### ISSUE THREAD

**Issue by moorl** [shopware/platform#2212]
### Please describe the feature you would like to see implemented.

For some reasons our customers want to serve upload fields within the register form.

Here we need the following attribute:
```
enctype="multipart/form-data"
```

Actually we copy the whole form from the core template or resolve it with a little JS hack:
```
<script type="text/javascript">
   const registerForm = document.getElementsByClassName("register-form")[0];
   registerForm.enctype = "multipart/form-data";
</script>
```

Both solutions are working for now, but are kind of ugly. 

So I like to ask for an additional Twig block at this point:
https://github.com/shopware/platform/blob/6179a94fa19aa26b46e9d0c5d77b20bfa5c5bb5b/src/Storefront/Resources/views/storefront/component/account/register.html.twig#L13

Kind regards
Philipp

**Comment by iulianbeleiu** [comment]
I'll be working on this one.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
