### ISSUE TITLE
Backend Overview of Snippets limited to 25 only

### ISSUE THREAD

**Issue by Leeman92** [shopware/platform#2216]
### PHP Version

8.0.12

### Shopware Version

6.4.6.1

### Expected behaviour

When I edit snippets in the backend I want to be able to edit the snippets for every created language within shopware.
Either have them all load at once or have the option of a pagination

### Actual behaviour

It gets limited to only 25 languages
The default Limit is 25 sadly

### How to reproduce

Create 26 different Snippet-Sets within Shopware and try to change a snippet for all 26 languages. You will only be able to change the first 25 via the backend

**Comment by Leeman92** [comment]
The proper solution would be to probably add a pagination to it?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
