### ISSUE TITLE
dal:create:schema does not respect OneToOneAssociationField 

### ISSUE THREAD

**Issue by azngeek** [shopware/platform#2222]
### PHP Version

 7.4.15

### Shopware Version

6.4.5.1

### Expected behaviour

If a 1:1 relation is defined, a foreign key should be set the the created sql-schema.

### Actual behaviour

There is no foreign key defined in the schema when automatically created. Example. This is missing the foreign key. The example for this generated schema is below.

```
CREATE TABLE `order_refund` (
    `id` BINARY(16) NOT NULL,
    `payment_method_id` BINARY(16) NOT NULL,
    `comment` LONGTEXT NOT NULL,
    `order_id` BINARY(16) NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

I would expect this:

```
 CONSTRAINT `fk.order_id` FOREIGN KEY (`order_id`) REFERENCES `order` (`id`)
```

### How to reproduce

Create a schema with a 1:1 relation

```
    protected function defineFields(): FieldCollection
    {
        return new FieldCollection([
            (new IdField('id', 'id'))->addFlags(new PrimaryKey(), new Required()),

            (new LongTextField('comment', 'name'))->addFlags(new Required()),

            (new FkField('order_id', 'orderId', OrderDefinition::class))->addFlags(new Required()),
            new OneToOneAssociationField('order', 'order_id', 'id', OrderDefinition::class, false),

            new CreatedAtField(),
            new UpdatedAtField()
        ]);
    }
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
