### ISSUE TITLE
Criteria: hasAssociation does not support recurisve dot syntax

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2236]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

using:

```
$criteria->hasAssociation('orderCustomer.customer');
```

works the same as `getAssocation` recursively. Except that it returns `true` or `false` accordingly.

`getAssocation` cannot be used in this scenario, as that one also automatically adds the corresponding association.

### Actual behaviour

it only checks the first level.

### How to reproduce

see expected behaviour

**Comment by AndreasA** [comment]
If https://github.com/shopware/platform/issues/2237 is implemented then this could be implemented quite easily by using this for `hasAssociation`:  `return null !== $this->getAssociation($path)`

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
