### ISSUE TITLE
Admin menu - Third level (and maybe fourth etc.) flickering in left menu bar, if not collapsed

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2238]
### PHP Version

8.1

### Shopware Version

6.4.7.0

### Expected behaviour

No flickering of third and further levels of the admin menu in non collapsed state.

### Actual behaviour

Menu flickers at third level (and maybe higher) in non collapsed mode.

### How to reproduce

When using the admin menu left bar, if it isn't collapsed, with a third level, so e.g. `Catalogues` --> `Vendor` --> `Item 1` produces `flickering`.

Now if I open `Catalogues` on the left menu bar and then `Vendor` by clicking on them. So far everything is fine.

However, if I now try to select an item in the third level, then that level is flickering (appearing and disappearing). with the hover menu and the collapsed menu it works correctly.

**Comment by AndreasA** [comment]
As it might be relevant I am using `Chrome` version `96.0.4664.93` on Mac OS Monterey

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
