### ISSUE TITLE
No custom field sets for folder type categories?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2250]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

Allow editing of custom field sets also on folder types - or at least at a setting to allow it.

I want to use custom fields to add additional information on footer navigation top categories (and maybe sub-categories). As those are not really pages that are usable, it makes more sense to set them as type folder.

However, custom fields are currently not shown, if the category is of type folder. 

Seems like an unnecessary arbitrary limitation as even links show the custom fields.

### Actual behaviour

Custom field sets are not shown for categories of type folder.

### How to reproduce

- Add custom fields to category entity
- Open a category
- Change type to folder
- Now custom field sets are hidden.

**Comment by bak3rmak3r** [comment]
confirmed

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
