### ISSUE TITLE
Wrong theme name in theme.json if you are using a lowercase name

### ISSUE THREAD

**Issue by adrianengel** [shopware/platform#2257]
### PHP Version

7

### Shopware Version

6

### Expected behaviour

I create a theme using my terminal. For the theme name I use "demotheme". Shopware creates a folder called "Demotheme" and create a theme.json with the correct name(first letter uppercase).

### Actual behaviour

I create a theme using my terminal. For the theme name I use "demotheme". Shopware creates a folder called "Demotheme" and Shopware create a theme.json with the incorrect name(first letter lowercase).

### How to reproduce

- create theme with your terminal
- use demotheme for the name
- Folder is called Demotheme and in theme.json you will find "@demotheme"

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
