### ISSUE TITLE
Tabs for plugin configuration

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2268]
### Please describe the feature you would like to see implemented.

Add an option to add tabs for your plugin configuration.

### Example
![image](https://user-images.githubusercontent.com/20150243/149174993-dc4d1b7d-34fb-4540-a0ae-c2fccdf1bbc7.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
