### ISSUE TITLE
Additional charge for payment methods

### ISSUE THREAD

**Issue by weselben** [shopware/platform#2276]
### Please describe the feature you would like to see implemented.

Hello,

I would like to have introduced the function of markup on payment types. In Germany it is common to pass on the "cash on delivery" costs to the customer. And to list these extra as charges of the payment method

- Ben

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
