### ISSUE TITLE
Make product select field in backend order edit wider

### ISSUE THREAD

**Issue by peerlight** [shopware/platform#2282]
The product select field in backend order edit is too small to show full article names and distinct between similar items.

So make this field wider or better: use higher values for .sw-card {max-width: ...} when browser window width allows it. 

Even further: backend should make use of the space available on large screen ...

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
