### ISSUE TITLE
Cache clear does not propagate through servers with different database credentials to same database

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/platform#2302]
### PHP Version

7.4

### Shopware Version

6.4.7

### Expected behaviour

When I click clear cache in admin it clears caches for frontend servers. And I do not have to install additional software like a cache clear multiplexer!

### Actual behaviour

A cache namespace is cleared that isn't used by the frontend servers.

### How to reproduce

1. Have frontend server that serves anything but /api, uses db user frontend and uses redis cache
2. Have backend server that serves /api and uses db user backend and uses the same redis cache
3. Change cached content that clears cache tags or click on cache clear in admin
4. See two redis cache namespaces. One for frontend using cache id from frontend server (lots of keys), another one from backend server (just a few keys).

It reasons from using the database url as part of the cache id. Whatever your reasons are to include that database url in [here](https://github.com/shopware/platform/blob/bef037b23659459fead8dd99faa3fc002e8fa8a8/src/Core/Kernel.php#L354-L372) but it won't allow for such a setup which seems to be quite frequently used in clustered environments.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
