### ISSUE TITLE
CartPersister::load has unnecessary sales channel context requirement

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2318]
### PHP Version

8.1

### Shopware Version

6.4.8.0

### Expected behaviour

Allow CartPersister::load to be called without a sales channel context as it is possible one has the context token but not yet the sales channel context. This avoids an unnecessary requirement to the sales channel context.

As it removes a a parameter from the interface this might only be possible with a new major release.

### Actual behaviour

Currently the cart persister requires the sales cannel context to load a cart but it isn't used at all.

### How to reproduce

See code https://github.com/shopware/platform/blob/v6.4.8.0/src/Core/Checkout/Cart/CartPersister.php#L32

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
