### ISSUE TITLE
Product Listing ignores mainVariantId

### ISSUE THREAD

**Issue by luismarquesfreire** [shopware/platform#2323]
### PHP Version

7.4

### Shopware Version

6.4.6.0

### Expected behaviour

On **product listings**, **with filters applied**, the previews should show the **main variant** that is configured on mainVariantId of product. This works well without filters but when there are option filters, then the resolve previews is ignored.

The problem is in this code on `ProductListingLoader.php`:

```php
if (!$this->hasOptionFilter($criteria)) {
    list($variantIds, $mapping) = $this->resolvePreviews($ids->getIds(), $context);
}
```
The `hasOptionFilter` function checks for the `optionIds` filter on criteria and it is there when filters are applied on product listing.

Previews should always be resolved. If this covers another use case, then I suggest adding a **configuration variable** on the admin panel so we can control this behavior.

### Actual behaviour

When filters are applied, variant previews are not resolved and so the product listing shows random variants instead of the main variant id.

### How to reproduce

Perform filters and if configuration options are shown, the main variant id is not selected consistently. It has a random behavior and I suspect it depends on the order it is inserted in the database.

**Comment by taltholtmann** [comment]
Hello luismarquesfreire,
thank you for your inquiry.
The behavior you describe is currently the desired behavior. 
Example: A product exists in red and green variants, with the main variant green. If you now filter for red in the storefront, the main variant is ignored and only the variant that still matches is displayed.

If you want to change the behavior via a configuration, you are welcome to submit a feature request via our official issue-tacker issues.shopware.com/. 

The responsible product owner will then look at the behavior and process it further.

**Comment by TanjaBayer** [comment]
I also think this is kind of an inconsistency: the user configures to see main Variants instead of products, this is a active step he is taking, but once filters are applied this configuration is completely ignored.

But the even bigger problem in my opinion is that once the user sets a filter, the result which is returned is even the wrong child:

In my query I request a specific ID:
![image](https://github.com/shopware/platform/assets/30770185/24e2b463-b1c4-484f-b551-fc414b00b4c6)

But the resulting element has a different ID:
![image](https://github.com/shopware/platform/assets/30770185/724df508-e304-4726-aef6-b28770396e27)

In my opinion this is a bug

**Comment by danielomer** [comment]
Where is this mainVariantId stored in the db? I cannot find it

**Comment by TanjaBayer** [comment]
It is stored in the `parentId` column in the product table

**Comment by rkconsulting** [comment]
1.5 years later and this topic is still ignored, what is going on, Shopware?  The current behavior is not as described by @taltholtmann .  If the main variant of a product has the option that is selected via filter, the filtered listing should STILL feature the main variant if that has been configured, yet it picks the displayed variant seemingly at random!  In other words, unfiltered I see the main variant (as configured), but if I then select a filter option that ALL variants of the product definitely have, then -sometimes- a completely different variant is featured in listing.  Why??  I assume it goes by order in the database, which might as well be random.  This makes no sense!  Guys, please reopen this ticket and fix this as soon as possible!  Thank you!

**Comment by thompalstra** [comment]
Well, I figured out what's going on. Apparently this is "intended behavior", in `shopware/core/Content/Product/SalesChannel/Listing/ProductListingLoader.php` on line 88 I'm seeing this code:
```
        $hasOptionFilter = $this->hasOptionFilter($criteria);
        if (!$hasOptionFilter) {
            $mapping = $this->resolvePreviews($ids->getIds(), $context);
        }
```

When I change the above to the following:

```
        $hasOptionFilter = $this->hasOptionFilter($criteria);
        // if (!$hasOptionFilter) {
            $mapping = $this->resolvePreviews($ids->getIds(), $context);
        // }
```
The correct variants are displayed. No clue why Shopware has chosen to explicitly ignore the "resolvePreviews" method when option filters have been applied.

UPDATE

Further backtracing led me to find the `shopware/core/Content/Product/SalesChannel/Listing/ProductListingFeaturesSubscriber.php` on line 572. Here we can see that the criteria is always extended with "product.propertyId":

```
        foreach ($grouped as $options) {
            $options = array_column($options, 'id');

            $filters[] = new MultiFilter(
                MultiFilter::CONNECTION_OR,
                [
                    new EqualsAnyFilter('product.optionIds', $options),
                    new EqualsAnyFilter('product.propertyIds', $options),
                ]
            );
        }
```

This obviously seems intentional, but the `hasOptionFilter` seems to always be true when any form of filtering is applied, with the exception of price, filtering by price with variants doesn't work at all.

**Comment by thompalstra** [comment]
@taltholtmann 
> Hello luismarquesfreire, thank you for your inquiry. The behavior you describe is currently the desired behavior. Example: A product exists in red and green variants, with the main variant green. If you now filter for red in the storefront, the main variant is ignored and only the variant that still matches is displayed.
> 
> If you want to change the behavior via a configuration, you are welcome to submit a feature request via our official issue-tacker issues.shopware.com/.
> 
> The responsible product owner will then look at the behavior and process it further.

This is obviously not the case for most products.

1. Create a category with 1 product.
2. Give the main product size = M (variants will inherit)
3. Generate 4 variants by color (green, red, blue orange)
4. Go to storefront presentation and select green as main variant

Filtering in the category on the storefront where size = M, will show some random other colour.

How is this "intended behaviour"? We're not filtering by a property of a variant, we're filtering by a shared property.
