### ISSUE TITLE
Display article number in Product Dropdown (Admin/CMS)

### ISSUE THREAD

**Issue by SimonNitzsche** [shopware/platform#2331]
### Current Behavior
We have a hard time when assigning an Article to a CMS-ProductBox within the Layouts.
Due to there being no article number in front of the name it is difficult to find the one we want to assign.

### Wished Behavior
Show the article number in front of the article name in the CMS-ProductBox ProductDropdown.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
