### ISSUE TITLE
Show net and gross price on the Admin>Catalog>Products Overview

### ISSUE THREAD

**Issue by SimonNitzsche** [shopware/platform#2332]
### Current behavior
Only the gross price is shown as an column even when set to exclude VAT (from what it looks like)

### Wished behavior
Have a column with net price and a column with gross price in the overview.
Or select the price based on the setting (include VAT / exclude VAT)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
