### ISSUE TITLE
ImageStruct::setMedia - make MediaEntity nullable

### ISSUE THREAD

**Issue by moorl** [shopware/platform#2335]
### PHP Version

7.4

### Shopware Version

6.4

### Expected behaviour

In some cases shop owners remove images form the media manager. If the image is bounded to any CMS element, the storefront can't be loaded. 

php.CRITICAL: Uncaught Error: Argument 1 passed to Shopware\Core\Content\Cms\SalesChannel\Struct\ImageStruct::setMedia() must be an instance of Shopware\Core\Content\Media\MediaEntity, null given

### Actual behaviour

-

### How to reproduce

-

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
