### ISSUE TITLE
Use interfaces instead of Abstract* classes wherever possible and use interfaces for all services (e.g. services to be used in decoration)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2347]
### Please describe the feature you would like to see implemented.

Currently there are a lot of services, that use Abstract* classes to be used in decorators, e.g. AbstractSystemConfigLoader, various routes etc.
However, the abstract class usually only defines some public abstract methods. This makes the abstract class superfluous and an interface would be enough and more helpful as e.g. a service can implement multiple interfaces which is not the case with Abstract* classes.

Furthermore, in order to easily be able to decorate services, nearly all should use interfaces.

This might be related to https://github.com/shopware/platform/issues/454

**Comment by keulinho** [comment]
It was a deliberate design decision to use `abstract classes` instead of `interfaces` where service are designed to be decorated. The reason is that we have the possibility to add new methods to the abstract classes without necessarily breaking all decorators. 
For detailed information on the decision and the pattern refert to [this ADR](https://github.com/shopware/platform/blob/trunk/adr/2020-11-25-decoration-pattern.md).

The reason why there are no interfaces for most services is basically the same -> to offer us more flexibility and making it easier to maintain and further evolve shopware in the future. Adding a `interface` locks us in a way more rigid contract, because  with a interface we can't introduce changes that would break implementation of that interface (that is mainly adding new methods, and adding new optional params). For plain services without an interface we promise that we won't change the service in a way that breaks users/callers of that service, however we may introduce changes that are backward compatible with callers, but may break in cases where the service in question was extended. 

In cases where we designed the service to be decoratable we added a AbstractClass (or an Interface for older implementations) that make decorations possible. In all other cases the service was not designed to be decorated, and we do not promise that we won't break decorators that work by extending the concrete service.

As in Software Architecture / Design this is all about tradeoffs. Here the tradeoff is between the extensibility of the system by plugins and the evolvability and maintainability of the system in the future. By our general approach to the issue stated above i think we have found a quite balanced standpoint. For sure we value external developers and the ecosystem in general, but we also want to be in a position to continually evolve the system instead of having to rewrite it from scratch again. So i think the ecosystem should also benefit from this perspective (by not having to go through another rewrite).

So IMHO there are no reasons to change our general standpoint on that matter, as stated above. But we are always open to discuss specific cases where a service maybe should be decoratable and add an abstract class if we see the use case behind it.

This is probably not the answer you wanted to hear, but i hope you can understand our point of view here. :v:

**Comment by AndreasA** [comment]
@keulinho However, from what I know the same is possible with interfaces, e.g. this works just as well:

```php
<?php declare(strict_types=1);

interface C {
    public none(): void;
}

interface A
{
 public function abc(string $a): void;
}

class B implements A {
    public function abc(string $a, ?C $c = null): void
    {
        
    }
}

$b = new B();
$b->abc('abc');
```

**Comment by AndreasA** [comment]
@keulinho OK. so do I understand this correctly and the main reason is that you can add additional parameters?

That is also possible wiith interfaces, e.g. this works just fine:

```php
@keulinho However, from what I know the same is possible with interfaces, e.g. this works just as well:

```php
<?php declare(strict_types=1);

interface C {
    public function none(): string;
}

interface A
{
    public function abc(string $a): string;
}

class B implements A 
{
    public function abc(string $a, ?C $c = null): string
    {
        return '';
    }
}

$b = new B();
$b->abc('abc');
```

if your remove the default value `= null` though it will fail but that is also the case for the abstract class.

And regarding adding additional methods, well if they are `abstract` it will fail just as well. except if there is a default implementation but that would break the decoration chain if even one service doesn't implement it which is probably the only advantage of not using interfaces but that could be done by using `separate` services instead in most cases. That way it would not break old implementations either.

Regarding `getDecorated` that is also possible with interfaces. after all an interface could require it if necessary.

With interfaces, you could split it into multiple interfaces and start a separate decoration chain. On the contrary, it might actually make more sense for decorations to keep the required methods small and e.g. start a separate service. As that makes it easier to decorate.

And it also avoids that the service might call its own methods with `$this->method()` which will be tricky to decorate as such a call bypasses the decoration chain. So it is actually way more helpful to create a new service for this anyway instead of adding more methods to be decorated.

**Comment by AndreasA** [comment]
However, I understand if you do not add interfaces to all services as that makes changing / extending them more complicated (probably).

However, the same issue applies with their use. You cannot just willy nilly change arguments anyway as the service might be called in a plugin and therefore does not provide new arguments, so it might actually be a good idea to have interfaces for nearly all services to ensure all changes stay backward compatible at the beginning.

The same is true for abstract classes that can be used to decorate services.

**Comment by AndreasA** [comment]
@keulinho But ok. in most cases using abstract classes should be fine anyway but my points from above still apply too 😄 
and I also understand that you do not want all services to be that easily decoratable (meaning backwards compatible decoratable). However, it would be nice if various would be like e.g. CartService, CartPersister etc. Optionally, add a lot more events 😄 

Btw. regarding adding methods one potential solution (but more effort) would be to use interfaces and traits. the trait could provide the `getDecorated()->loadV2()` method e.g. For a default implementation it could either do nothing or provide an implementation for getDecorated and to initialize it, e.g. setDecorated or construct. Or just create a new service/interface for the method. 
But I understand that with your current solution the trait isn't necessary in that scenario (and a not service isn't necessary, even if it would make more sense) but e.g. the trait / interface solution can be helpful in general, e.g. for updated/created fields etc.

**Comment by AndreasA** [comment]
In any case I am going to close it for now as it was a design decision.
