### ISSUE TITLE
Add event to modify active rule IDs, cart and tax state after cart process iterations are done, e.g. to call external services

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2348]
### Please describe the feature you would like to see implemented.

Some features like e.g. using FedEx / UPS APIs to retrieve the shipping charges on the fly might depend on the cart total for insurance purposes etc. So it is quite tricky to memoize them or cache them during cart processor iterations.

I am aware that this is not a perfect solution but an easy solution would be that after the cart, rules, tax state are fully processed there is an event that allows developers to change all these values, however they want and therefore e.g. call UPS API there and adjust delivery charges accordingly. Yes, this might change rules but that is why the rules could also be adjusted there or not, if it isn't necessary (e.g. by defining in a README that shipping charges cannot be part of the rule determination) - or maybe always redetermine active rules after the event is called.

Tax state would be nice to adjust there as there are multiple reason for it to change, e.g. a company, country and a valid tax ID (validated against the corresponding API) are in use.

**Comment by AndreasA** [comment]
I would also be happy with a better solution but I don't think there is any without readjusting the complete cart / rule loading behavior.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
