### ISSUE TITLE
subcategories menu issue

### ISSUE THREAD

**Issue by SathisKS** [shopware/platform#2363]
### PHP Version

8.0.15

### Shopware Version

6.4.8.0 and 6.4.8.1

### Expected behaviour

Move to subcategories menu in before and after in previous categories 

### Actual behaviour

We can't move "sw-tree-item__label" to create a new category in shopware versions like 6.4.8.0 and 6.4.8.1.

### How to reproduce

Pre-condition
 1. Navigate to Catalogues > Categories
 2. Create new Categories
 3. Now move to create new Categories that time we can't move.
 If you need more information kindly refer to the attached video

https://user-images.githubusercontent.com/49578962/154043297-41e50084-c25d-441c-a666-1d8d2c4d3898.mp4

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
