### ISSUE TITLE
TestBootstrapper should also use EnvironmentHelper utility instead of accessing $_SERVER directly (at least for DATABASE_URL)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2364]
### PHP Version

8.1

### Shopware Version

6.4.8.1

### Expected behaviour

TestBootstrapper should also use the EnvironmentHelper to retrieve the database URL (and any others) and not bypass it.

### Actual behaviour

TestBootstrapper currently bypasses EnviornmentHelper utility when retrieven $_SERVER variables.

### How to reproduce

See TestBootstrapper class and/or add an EnvironmentHelper transformer for e.g. the database_url and it will fail to be executed

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
