### ISSUE TITLE
Clone entity (order) with extension (many to one) fails as the foreign key is not cloned

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2370]
### PHP Version

8.1

### Shopware Version

6.3.5.2, probably also newer.

### Expected behaviour

When cloning an order e.g. with an additional state field that information is lost, as the foreign key is not cloned as extensions do not just include the ID, so the ID is lost.

see also https://issues.shopware.com/issues/NEXT-12524

I am mostly interested in an update regarding this.

### Actual behaviour

Data is lost, e.g. when a state is added to order and it is cloned (edited).

### How to reproduce

Add a state machine field extension to the order, assign a value, edit/clone it and the data is lost.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
