### ISSUE TITLE
Number Range for Categories

### ISSUE THREAD

**Issue by ayZagen** [shopware/platform#2411]
### Please describe the feature you would like to see implemented.

It would be great to have number range settings for categories.
Common use case would be creating easily queryable URLs in a headless structure. For ex:
```
https://mysite.com/electronics-c-11
``` 
in this url `c-11` is the category id.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
