### ISSUE TITLE
Add product number to order-line-items in admin's order detail view

### ISSUE THREAD

**Issue by SimonNitzsche** [shopware/platform#2417]
### Please describe the feature you would like to see implemented.

Only Quantity, Label, and prices are shown. However we use the product number to identify products instead of their name.
![image](https://user-images.githubusercontent.com/6717311/161219002-75383194-e5da-49e6-aeb1-c7ebdf67cb25.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
