### ISSUE TITLE
Product category dialog is overlayed by media section

### ISSUE THREAD

**Issue by epsreps** [shopware/platform#2428]
### PHP Version

7.4

### Shopware Version

6.4.10

### Expected behaviour

Like in 6.4.8 the dialog for selecting the category in a product should overlay the following media section.

### Actual behaviour

In 6.4.10 the category select dialog is cutted and unreachable by the following media section. 

### How to reproduce

Tested with fresh shopware 6.4.10 install and demo shop data.
![Bildschirmfoto 2022-04-17 um 21 13 59](https://user-images.githubusercontent.com/3583919/163729094-e681d2a5-d11c-4f0b-a9b9-11694015d1a0.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
