### ISSUE TITLE
Creating new customer via Administration

### ISSUE THREAD

**Issue by jmedynski** [shopware/platform#2431]
### PHP Version

7.4

### Shopware Version

6.4.10.1

### Expected behaviour

Correct creation of a new customer via Administration Panel.

### Actual behaviour

An error occurs when I try to save a new customer:

api/customer
>"code":"0",
"status":"500",
"title":"Internal Server Error",
"detail":"Provided language 2fbb5fe2e29a4d70aa5854ce7ce3e20b is not in list of available languages: 1a9cee9450244cd6a90d7541246debd9"

### How to reproduce

Create a saleschannel with one language that is not the default system language. For example, when the system default language is English, create with German.

Fill out the new customer creation form in the administration panel and select the created saleschannel with one language other than the default system language and save.

**Comment by moorl** [comment]
Did you changed/deleted the default language from the shopware installation?

**Comment by jmedynski** [comment]
@moorl nope, tested on clean and fresh instances.

**Comment by kurtinge** [comment]
We are experiencing this issue as well.

The error comes from the new BaseContextFactory.
https://github.com/shopware/platform/blame/trunk/src/Core/System/SalesChannel/Context/BaseContextFactory.php#L329

Could a solution be to just fall back to the default language of the saleschannel instead of throwing an exception ?

**Comment by silviokennecke** [comment]
Just a small Update: In my tests in 6.4.10.1 the customer was created anyway. In 6.4.16.1 the customer is not created anymore.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
