### ISSUE TITLE
CMS-App rendering not as expected

### ISSUE THREAD

**Issue by NinjaArmy** [shopware/platform#2438]
### PHP Version

7.4

### Shopware Version

Shopware 6.4

### Expected behaviour

Within the blocks you define slots for the elements with slot names. The expected behaviour would be that the first slot you define in a block will be rendered first.

### Actual behaviour

The actual behaviour is that the slots in a block are rendered alphabetically. There is no information for this in the docs.

### How to reproduce

Clone the repository https://github.com/NinjaArmy/sw6-cms-app-example and take a look at the behaviour. 2 blocks complete identical but the slot names are different. Also there is a detailed description in this repository

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
