### ISSUE TITLE
Listing price issue with advanced pricing

### ISSUE THREAD

**Issue by zaifastafa** [shopware/platform#2440]
### PHP Version

7.4.29

### Shopware Version

6.4.10.1

### Expected behaviour

Correct calculated "From" price is shown in the listing

### Actual behaviour

Correct calculated price "From" is not shown in the listing. 

### How to reproduce

1. Create a product with advance pricing 
2. Add a price matrix with quantity

- From 1 to 10 => 900 EUR
- From 10 to infinity => 750 EUR

= correct from price is shown in listing

Now change the price of 1 to 10 => 200 EUR
the price is still shown as 750 in the front, whereas the lowest price now is 200 so it should show that in the "From" listing. 

P.S. The price linking also does not work automatically when changing the prices in advance pricing. Even if th prices are linked, they need to change unlinked and linked again for the price to update.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
