### ISSUE TITLE
Cannot read properties of undefined (reading 'data') on image save in layout editor

### ISSUE THREAD

**Issue by DeniseNoLimits** [shopware/platform#2446]
### PHP Version

7.4.25

### Shopware Version

6.4

### Expected behaviour

I want to add an image to a block in the layout editor. I add the block, do NOT configure anything, get the error "Aufgrund folgender Fehler konnte nicht gespeichert werden: Einige Blöcke wurden nicht ausreichend konfiguriert.". Then I add the necessary configurations and save the layout again with no error.  

### Actual behaviour

I want to add an image to a block in the layout editor. I add the block, do NOT configure anything, get the error "Aufgrund folgender Fehler konnte nicht gespeichert werden: Einige Blöcke wurden nicht ausreichend konfiguriert.". Then I add the necessary configurations and save the layout and then I get the error "Cannot read properties of undefined (reading 'data')" which is not  fixable. I have to delete the image element and add it again and add the correct config BEFORE I save it the first time to get rid of the error. 

### How to reproduce

as described in actual behavior.

**Comment by Alfagun74** [comment]
got the same issue

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
