### ISSUE TITLE
Button to re-send order confirmation emails

### ISSUE THREAD

**Issue by royandre** [shopware/platform#2452]
### Please describe the feature you would like to see implemented.

Requesting a function within the order to let the store admin re-send the order confirmation email.

The button could be on the order view page, top right, and simply trigger sending the order confirmation to the customer's email address.

There exists 3rd party plugins for this function - however it feels more like a core function (and other eCom platforms has it as a core function).

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
