### ISSUE TITLE
Structured Data: Cross-Selling products within a slider are interpreted as the product on the product page

### ISSUE THREAD

**Issue by SimonNitzsche** [shopware/platform#2459]
### PHP Version

7.4.10

### Shopware Version

6.4.10

### Expected behaviour

Count the entries as seperate products or simply remove the structured data from the product slider of cross-selling.

### Actual behaviour

At the moment a product contains multiple ean of different products for structured data.
This can be seen for example on the [Google Test for Rich-Results](https://search.google.com/test/rich-results):
![image](https://user-images.githubusercontent.com/6717311/166205103-5d0b5cd4-09be-410c-b575-7eae4c61f71c.png)

All of those entries are linked to one single product.

### How to reproduce

Add a cross-selling product slider with entries to a product page. (From what it looks like they are not generated for demo data [automated test]?)

Analyze the structured data generated with a tool like [Google Test for Rich-Results](https://search.google.com/test/rich-results)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
