### ISSUE TITLE
Administration: Conditions for Plugin Config

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2460]
### Please describe the feature you would like to see implemented.

Show fields in the plugin config if certain conditions match, e. g. if field x is checked, show field y

**Comment by PheysX** [comment]
Same for customFields 😄

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
