### ISSUE TITLE
AbstractProductPriceCalculator should implement ResetInterface instead of implementation with a default implementation to call reset on the decorated service.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2471]
### PHP Version

8.1

### Shopware Version

6.4.11.1

### Expected behaviour

The current implementation of \Shopware\Core\Content\Product\SalesChannel\Price\ProductPriceCalculator has added a ResetInterface, which is fine in general. 
However, the tags of the service are inherited by decorators, so if the decorating service does not implement reset as well, it will fail.

There are probably multiple solutions to this but as you use Abstract* classes for exactly such a purpose, the easies solution would be to make the AbstractProductPriceCalculator implmenet the ResetInterface, with a default implmentation:

```
    public function reset(): void
    {
        $this->getDecorated()->reset();
    }
```

This default implementation can then be adjusted in the ProductPriceCalculator implementation.

### Actual behaviour

See expected behavior

### How to reproduce

see expected behavior

**Comment by keulinho** [comment]
Sounds reasonable to me, can you provide a PR?

**Comment by AndreasA** [comment]
@keulinho Sure, can't guarantee when though. Hopefully this week.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
