### ISSUE TITLE
Breaking change to StringFieldSerializer - Check for empty value after trim, this means a string like " " now fails update/create

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2472]
### PHP Version

8.1

### Shopware Version

6.4.11.1

### Expected behaviour

The StringFieldSerializer should not fail the trim check until at least 6.5 as this is actually a breaking change, as I cannot store " " anymore. Sure in most cases this is not a good value to store anyway but as we import data where either first name or last name can be empty (not both), as a workaround for the `Required` check, we stored a space, until the data was fixed by the customer later on.

In order to avoid a breaking change:
- Remove trim check from customer  and add it to the registration validation as that was why it was added in the first place.
- And add a feature flag to trim it in the value in the string field serializer, with a deprecation information regarding 6.5 and disable it for now.

### Actual behaviour

Trying to store a space for firstName / lastName in the customer entity now fails, which did not before and therefore this is a breaking change.

### How to reproduce

see above.

**Comment by OliverSkroblin** [comment]
Hey @AndreasA,

I was looking at the issue and came across the following [commit](https://github.com/shopware/platform/commit/d36c067ec354333e58a0411b04c434023ad2d7f3)

Here, we added a `trim()` in the `StringFieldSerializer`, which fixed a bug in the validation of the `AllowEmptyString`. Since it is not intended by the developer to support an empty string for these fields, we have implemented the `trim` check here, since we had not considered it in the initial commit (2020).

I will revert the change with the next version

**Comment by AndreasA** [comment]
@OliverSkroblin It isn't that huge a breaking change and as mentioned it definitely makes sense as a feature flag, but it should probably be avoided as it can have some impacts elsewhere.

**Comment by shyim** [comment]
https://github.com/shopware/platform/commit/1b6cfe5db53019943bb1c4da9e6bdb56b2933b26
