### ISSUE TITLE
1:1 extension associations should be easier to handle in admin / general by adding empty entity if missing

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2474]
### Please describe the feature you would like to see implemented.

Using 1:1 extension associations can be quite annoying sometimes to adjust the admin correctly (adding new empty entity to create, if it doesn't exist yet - e.g. on update or on create).

This can be an issue during admin and also when retrieving existing entities and storing such data (check if ID exists, add it etc.).
It would be nice if in such scenarios an empty entity could be pre-added to the entity as extension and to the prepared admin entity, if it does not yet exist.

This should not be done by default, as it might not be helpful in all scenarios but it would be nice to have it optional, e.g. by using a flag in the entity extension.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
