### ISSUE TITLE
NEXT-21581 | Tax is not recalculated if shipping cost is changed from the order backend

### ISSUE THREAD

**Issue by zaifastafa** [shopware/platform#2484]
### PHP Version

7.4

### Shopware Version

6.4.11.1

### Expected behaviour

Correct shipping tax is recalculated and adjusted in the total amount. 

### Actual behaviour

When changing the shipping cost from the backend on order edit, the shipping total is recalculated but the shipping tax is not. It still shows the old calculation and the order total also does not include the new shipping tax info. 

### How to reproduce

- Create an order with 7% tax with shipping cost for e.g 4.95
- Edit the order from the backend by changing the shipping cost to 15.9
- Upon saving, the order total is re-calculcated, but the tax still shows the old value. The tooltip also shows incorrect tax on the shipping, and the order total also does not adjust the tax correctly.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
