### ISSUE TITLE
Mass update (Mehrfachänderung): Do not make a preselection for property update to avoid mistakes

### ISSUE THREAD

**Issue by amenk** [shopware/platform#2488]
When a user tries to edit properties, they might not want to overwrite them, but add new properties.

Currently "Overwrite" is pre-selected, which would remove all non-selected properties by mistake.

![Properties](https://user-images.githubusercontent.com/1087128/168751305-b4694f17-167a-428d-a558-376a1d21ec62.png)

In most cases, "Add" would be a better choice.
As this might not be true for every use case, I would suggest to make no pre-selection in this dialog and let the user choose if they really want to overwrite or add new properties.

I would be nice to get some feedback for this feature, we then can probably provide a pull request.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by amenk** [comment]
This is not yet solved, but it's more a feature request and should be easy to fix.

Eventually I would tackle it on boost day.
