### ISSUE TITLE
Streamline data provided by flow builder events

### ISSUE THREAD

**Issue by niklaswolf** [shopware/platform#2494]
### PHP Version

8.1

### Shopware Version

6.4.11.1

### Expected behaviour

The data provided in the events for the flow builder should be the same, so that there are no unexpected cases when using the data in for example e-mail templates.

### Actual behaviour

For example the order data for different order related events is not the same, which is quite unexpected.

See an example here:

OrderPlacedEvent has the following order data:
https://github.com/shopware/platform/blob/6b21de1beb62e616dfbcf484152af480a512b9e5/src/Core/Checkout/Cart/SalesChannel/CartOrderRoute.php#L135

OrderStateChangedEvent has this order data:
https://github.com/shopware/platform/blob/6b21de1beb62e616dfbcf484152af480a512b9e5/src/Core/Checkout/Order/Listener/OrderStateChangeEventListener.php#L241

This leads to the unexpected error that lineItem images are present in a e-mail template when using the OrderPlacedEvent, but not when using a OrderStateChangedEvent.

### How to reproduce

- Have a mail template for orders where you use the lineItem-cover images
- use the same template in a flow with the trigger `checkout.order.placed` and one with the trigger `state_enter.order_transaction.state.paid`
- the mail that is send will contain the images in the first, but not the second flow.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
