### ISSUE TITLE
Let's make overriding admin modules possible

### ISSUE THREAD

**Issue by TimWuyts** [shopware/platform#2495]
### Please describe the feature you would like to see implemented.

It would be nice to be able to override admin modules using something like `Shopware.Module.override(moduleName, moduleManifest)`. This would be a similar approach as to overriding admin components using `Shopware.Component.override(componentName, componentLogic)`.

It's already possible in a certain way using `Shopware.Module.register(moduleName, moduleManifest)`, since the moduleName should be unique & only the first occurrence will be registered. But this is not always a viable & working solution, since it's not possible at the moment to alter the order of modules being registered.

This would bring additional benefits, example given:
- A clean way to override or extend (external) plugin code if needed, in order to make visual or functional improvements.
- A way to override admin related string translations (which is not possible at the moment), by inserting new or additional JSON snippets.
- ...

**Comment by seggewiss** [comment]
Thank you for your feature request.

This is something we can't offer in the near future. Overriding modules would come with several side effects.
Those side effects are for example but are not limited to:

- routes not being available but referenced by other modules
- existing router middlewares would break

That's why we cant offer this.

**Comment by TimWuyts** [comment]
Thank you for the additional clarification. Are there other ways or mechanisms in place (or will they be in the future), in order to hook into modules from plugin vendors? It would be great to:
- Modify existing code: add and/or override routes, change menu position/colors, ...
- Add and/or override string translations.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
