### ISSUE TITLE
Dokumentation link leads to Warning: Potential Security Risk Ahead

### ISSUE THREAD

**Issue by deBugger-** [shopware/platform#2500]
### PHP Version

not needed

### Shopware Version

relate to the current dokumentation

### Expected behaviour

visiting page without certificates warning 

and after accept a leading to this page https://docs.shopware.com/en/shopware-6-en/settings/snippets 

and  not to a external microsoft login page.

### Actual behaviour

Warning: Potential Security Risk Ahead

Firefox detected a potential security threat and did not continue to wiki.shopware.in. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

What can you do about it?

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

### How to reproduce

Clear browser cache / logins and so on.
open https://docs.shopware.com/en/shopware-6-en/tutorials-and-faq/changing-a-template

scroll down to the headline "Including snippets"

below second sentence: click on the word here 

by the way 
https://docs.shopware.com/en/shopware-6-en/settings/snippets
Here is a missing translation of the headline.  "Links einbinden" 

If you know a better place to report documentation issues, please leave a note.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
