### ISSUE TITLE
Option to define default http for <input-field type="url">

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2530]
### Please describe the feature you would like to see implemented.

`<input-field type="url">` is default always **https**. We'd like to have the option to set it default to **http**.

Example:
```xml
<input-field type="url">
    <defaultProtocol>http</defaultProtocol>
</input-field>
```

**Comment by tinect** [comment]
What is your reason for this?
My thinking is: while you should not use http on web, an option could be useless. You can paste http://-Link to make it switching, can't you?

**Comment by Zerotask** [comment]
Our use case is that we need for some fields per default **http** and Shopware always shows **https**. At the moment we're forced to update such fields from https to http. Having an option to define the default protocol would save time and decrease error proneness.

**Comment by tinect** [comment]
I understand you wish. But I'm more interested in the "use case" 🤔

**Comment by Zerotask** [comment]
That is the use case. You probably mean the reason, the "why http" but this is not of concern.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
