### ISSUE TITLE
Export & Import Plugin configurations

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2531]
### Please describe the feature you would like to see implemented.

It would be such a time saver if you could set a plugin configuration one-time and then export it (as zip, json etc) and import it somewhere else. We're working heavily with plugin configuration and have a lot of settings there. In local development we set everything up and then we have to do the same for staging and production etc.

**Comment by tinect** [comment]
I like the idea. There are existing tools for such tasks, f.e. https://github.com/FriendsOfShopware/shopware-cli

**Comment by Zerotask** [comment]
@tinect Thank you for that link. Unfortunately I can't see my requested feature there. Can you send the specific link for that functionality?

**Comment by tinect** [comment]
@Zerotask https://sw-cli.fos.gg/commands/project/
shopware-cli project config pull
shopware-cli project config push

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
