### ISSUE TITLE
Hide products after clearance, but keep the product page available

### ISSUE THREAD

**Issue by royandre** [shopware/platform#2537]
### Please describe the feature you would like to see implemented.

The current setting "Hide products after clearance" works fine, however in some setups one would like to also keep the product page available through the product's direct link.

This is especially useful for B2B sites which has products with important historical data that is important for businesses to be able to reach, and to find alternative products, download user manuals, etc.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
