### ISSUE TITLE
Better to sort by name instead of id of item in a list

### ISSUE THREAD

**Issue by isaklafleur** [shopware/platform#2546]
### PHP Version

latest

### Shopware Version

latest

### Expected behaviour

Most of your lists are not sorted alphabetic. I not sure if you sort by id instead of the name, small fix. Now it does not look professional.

![image](https://user-images.githubusercontent.com/10033653/174662423-7fbf509b-6c81-4940-b2fd-5093280aba82.png)

### Actual behaviour

should sort by name (based on the language of the user.

### How to reproduce

Most of the list in the admin side are not sorted.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
