### ISSUE TITLE
Better multi domain support

### ISSUE THREAD

**Issue by andersburn** [shopware/platform#2560]
### Please describe the feature you would like to see implemented.

Right now you can make a product and have It on the sales channels you want. 
You can make different translations of the text, title and so on. 

But you can't have 2 different texts on the same product, 2 different texts on 2 different sales channels. 
For SEO this is very important. 
 
Having a dropdown with saleschannels so you can make different settings(and text) on different sales channels. 
Having an option in the dropdown with all the saleschannels.
This function is used on plugins now. It would be great on theme settings too :) 

Prestashop does this very well.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
