### ISSUE TITLE
The frontend does not support Chinese keyword search

### ISSUE THREAD

**Issue by iecsp** [shopware/platform#2566]
### PHP Version

7.4.28

### Shopware Version

6.4.12.0

### Expected behaviour

Product name: 香港罗汉果
Search keyword: 罗汉果
Expected result:  "香港罗汉果"

### Actual behaviour

Search result: null

### How to reproduce

Create a new product named “香港罗汉果”, search keyword on the frontend "罗汉果"。

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
