### ISSUE TITLE
Filter products that are uncategorized (Admin Panel)

### ISSUE THREAD

**Issue by simonvanoordt** [shopware/platform#2571]
### Please describe the feature you would like to see implemented.

The bulk edit and filter options makes editing products fast and smooth. 

However, I would suggest a category filter option to find products that are not assigned to any category.

This filter option should be added to the current category filter. 

Cheers,

Simon

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
