### ISSUE TITLE
Add a 'dynamic product group' filter (products admin panel)

### ISSUE THREAD

**Issue by simonvanoordt** [shopware/platform#2572]
### Please describe the feature you would like to see implemented.

The bulk edit makes editing fast, but filtering options are still limited. One way to make almost any kind of filtering possible is to filter products by the dynamic product group they are in.

This could be similar to the category filter, except that you filter by dynamic product group. I see two major use cases:

1) With dynamic products group filter enabled, admins can filter products on attributes that are currently not supported in the filter, e.g. minimum order quantity and custom fields

2) With dynamic products group filter enabled, admins can bulk edit products using advanced queries without using SQL. Instead, they would create a dynamic product group and use this group to filter and bulk edit the products. E.g. filter products that have an MOQ between 50-100, a price between 1-5 and a rating of > 4.

Please let me know if it's not clear, because this could be a gamechanger for us. Now I have to ask the developer to run SQL queries for things that I could potentially do myself in the ShopWare admin panel.

Simon

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
