### ISSUE TITLE
availability for google feeds

### ISSUE THREAD

**Issue by wolf128058** [shopware/platform#2577]
### PHP Version

does not matter

### Shopware Version

6.x

### Expected behaviour

according to the specs of [google product feeds](https://support.google.com/merchants/answer/6324448?hl=en&ref_topic=6324338) you should not use "preorder" but rather "backorder" on products that were already available once.

and even more important: using those to values require a mandatory availability_date, that must be shown in feed, too

### Actual behaviour

the condition asks for things like product.deliveryTime and product.restockTime, but does not display a availability_date

### How to reproduce

just create a feed with that template and some products fitting to those conditions

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
