### ISSUE TITLE
See all folders in the media manager

### ISSUE THREAD

**Issue by AbeleDarius** [shopware/platform#2585]
### PHP Version

7.4.30

### Shopware Version

6.4.13.0

### Expected behaviour

An error occurred with future and issue NEXT-20815 now the button is always displayed

Problem in File 
shopware/administration/Resources/app/administration/src/module/sw-media/component/sw-media-library/index.js
row 314
is 
 const media =  this.mediaRepository.search(criteria, Context.api);
target
 const media = await this.mediaRepository.search(criteria, Context.api);

### Actual behaviour

More button is always displayed even if no data is available

### How to reproduce

More button only displayed if images (files) or folders can still be loaded

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
