### ISSUE TITLE
VAT-ID per-customer vs. per-address

### ISSUE THREAD

**Issue by laf0rge** [shopware/platform#2591]
### PHP Version

7.4.30

### Shopware Version

6.4.12.0

### Expected behaviour

it seems that the back-end data model supports EU-VAT-ID as a property per address (ee order.deliveries[0].shippingOrderAddress.vatId).  This is correct, as a single customer may have multiple delivery addresses in different countries, and hence different VAT-IDs per country.

### Actual behaviour

It seems that the VAT ID entered by the customer in the default storefront is not stored/reportred in the order.deliveries[].shippingOrderAddress.vatId (nor in the order.billingAddress.vatId) but it is stored in the order.orderCustomer.vatIds[] list.

At least when queryin the order via the API (for example to export it into the company ERP system), I see this odd behaviour.

### How to reproduce

Default shopware 6.4.12.0 installation with default storefront.  Just enable the B2B tax-free shipping for a few EU countries and place an order via the frontend, then query that order ID via the API.

**Comment by lutek** [comment]
just vote :) https://issues.shopware.com/issues/NEXT-20028

**Comment by laf0rge** [comment]
thanks, I just did. Was not aware there was a related issue on shopware.com already.  I find it rather shocking that such an (from my point obvious) feature existed and was deliberately removed.  Also, the fact that the shippingOrderAddress model still contains a vatId field that's no longer populated (without mention in the API docs or anywhere) is quite misleading.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
