### ISSUE TITLE
Disabling Inventory/Stock Management for specific Products

### ISSUE THREAD

**Issue by Alfagun74** [shopware/platform#2603]
### Please describe the feature you would like to see implemented.

I run a candle Business. I cast custom candles specifically how my customers order them. They can choose the color and fragrance of said candles in my shop. Thus i wont produce candles on stock that have not been ordered and the inventory system is completely useless to me.  
  
The Feature i propose is a checkbox to disable the inventory management system for some articles entirely so i dont have a counter of how many candles are in stock.

**Comment by lutek** [comment]
https://docs.shopware.com/en/shopware-6-en/catalogues/products?category=shopware-6-en/catalogues#deliverability

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
