### ISSUE TITLE
Empty shipping cost (hidden line) after checkout

### ISSUE THREAD

**Issue by lutek** [shopware/platform#2605]
### PHP Version

7.4

### Shopware Version

6.4.12.0

### Expected behaviour

in storefront twig template: component/checkout/hidden-line-items-information.html.twig

line with 
```
         data-shipping="{{ cart.deliveries.shippingCosts.sum().totalPrice }}"
```
should return shipping cost

should be there this variable?:
```
         data-shipping="{{ cart.shippingCosts.totalPrice }}"
```

### Actual behaviour

returns null

### How to reproduce

Create order and check html data (detected on google analytics events)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
