### ISSUE TITLE
shipping roule ignores artikles marked as shipping free

### ISSUE THREAD

**Issue by deBugger-** [shopware/platform#2610]
### PHP Version

8.0

### Shopware Version

6.4.13.0 

### Expected behaviour

As in SW5 all basket values should be to count together to get the shipping price. 

### Actual behaviour

Price shipping matrix "unrestricted"  should not ignore the article markup "shipping free" labeled articles. 

### How to reproduce

Repair a fresh sw6
- create article 5€
- create article 5€ mark it as shipping free (Deliverability Label: Free shipping: true)
- add a tax (non tax at all)
- deactivate or delete all shipping rules

Now create new shipping rule
	 
Name: Standard_2
Position:0
Active: true
Delivery time: 1-3
Availability: Always valid (Default)
Tax calculation type: Fixed
Rate: choose the previously created Non Tax at all

(Note a main headline for the shipping rules section is missing. But this does not belongs to the here reported bug.)

Create a price matrix -> select Cart price

first row:
Cart price from... : 0
to... : 9,99
4 (gross) 4 (net)

second row:
Cart price from...: 9,99
to...: **∞** 
0 (gross) 0 (net)

save

Switch to customer view

add article 5€ to basket
add article 5€ (Previously marked as shipping free)

Shipping cost is about 4. The price matrix ignores the shipping free article.

**Comment by deBugger-** [comment]
Yes, you can solve this basket issue with the rule builder. A note about the ignoring article markup "shipping free" is needed. 
A "Always valid (Default)" != "Always valid (Default)" but ignoring article markup "shipping free: yes"

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
