### ISSUE TITLE
Message queue hangs on invalid WarmupMessage

### ISSUE THREAD

**Issue by htuscher** [shopware/platform#2611]
### PHP Version

8.1

### Shopware Version

6.4.10.0

### Expected behaviour

The message consumer should ignore invalid messages and continue working.

### Actual behaviour

The message consumer dies after the message `cache-hit: routing-domains` without an error message or log entry, even in verbose mode.

### How to reproduce

Just issue `bin/console http:cache:warm-up` it will generate WarmupMessages for the saleschannel `default.headless0` those messages lead to the dying worker.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
