### ISSUE TITLE
Structuring element / Entry point are not displayed in the category tree

### ISSUE THREAD

**Issue by Novusvetus** [shopware/platform#2612]
### PHP Version

8.0.18

### Shopware Version

6.4.13.0

### Expected behaviour

Whem I insert a link in the tree, I want to redirect from there to any category. Even if it is a sub element of a structuring element.

### Actual behaviour

Structuring element are not listed in the destination selection field and so the corresponding subelements are not reachable.

### How to reproduce

- Create a new categorie.
- Choose category type "Link"
- Choose Link type "Internal"
- Choose Entity "Category"
- Try to choose a category, that is a sub category of a structuring element

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
