### ISSUE TITLE
Non products on delivery_note

### ISSUE THREAD

**Issue by Schrank** [shopware/platform#2616]
### PHP Version

8.1

### Shopware Version

6.4.12

### Expected behaviour

When creating a delivery_note I expect all product on it - and nothing else.

### Actual behaviour

Every line item is rendered, that includes:
- shipping
- discounts
- promos

### How to reproduce

Create an order with a discount and shipping costs, see three line items:
- product
- promo
- shipping cost

on delivery_note

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
