### ISSUE TITLE
"Delete unused media" Button

### ISSUE THREAD

**Issue by Raembozaemb** [shopware/platform#2621]
### Please describe the feature you would like to see implemented.

A "Delete unused media" button could be implemented in the media management.

Example functionality:
1. User opens the media folder "Product Media"
2. User clicks the "Delete unused media" button
3. A prompt opens "34 unused media objects found. Do you really wish to delete every unused media object in the folder "Product Media" and all its sub-folders?"
4. After confirming, the media objects are deleted

![image](https://user-images.githubusercontent.com/73197718/181192498-b1bbb043-9e2d-42f0-9056-25d6ee7987d1.png)

**Comment by tinect** [comment]
Due to plugins, this function is highly problematic.
I'd disagree to add such a button into admin because determining usage of images is not save enough.
f.e. if there are custom cms-elements accessing images, these will never take as used.

Additionally, added images by custom HTML (footer f.e.) are also not taken.

I highly recommend never to use the specific command ;-)

**Comment by PheysX** [comment]
The command is so dangerous to use. There should be a danger note: "Dont use it".

Does the command find cms used images at all? Or just even customField images?

**Comment by Raembozaemb** [comment]
Maybe you are right. I only use automated tools to fill Shopware, so it quickly fills with media, often some that is not needed the other day.

But if it is implemented for the current folder only, it is less of a security risk.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
