### ISSUE TITLE
Apps - Should be installable in the same way as plugins - static-apps like static-plugins and composer repository from story

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2629]
### Please describe the feature you would like to see implemented.

Currently all apps land in the `custom/apps` folder. 

However, due to automated deployments, it should be possible to install them using:

- composer store repository
- using a static folder that is untouched by the extension manager.

That way e.g. a developer can pre-install necessary apps during deployment but the end-user is still able to manually install additional apps without those two interferring. 
This should be easily doable by automatically creating a composer.json for apps by the repository. Except the target folder.

It is also possible to add static apps the same way as plugins that way. So a developer could create own apps and provide them during deployments easily.

Furthermore, not sure if this has already been fixed or not, but in 6.4.10.1 it was still the case: If an app folder is deleted, the app is not recognized as removed which can have weird side effects.
Especially,` in combination with the app refresh command not correctly detecting all existing plugins but uninstalling already installed plugins and adding only those that were not installed before - might have been fixed though?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
