### ISSUE TITLE
SCSS / JS compile during plugin update in extension manager admin interface can result in out of memory exception (1GB limit)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2631]
### PHP Version

8.1.0

### Shopware Version

6.4.10.1

### Expected behaviour

CSS / JS compilation should not reach any memory limits or timeouts that are put in place on most servers, if the admin extension manager is used.

Furthermore, the server has a limit of 1024MB set and it was still reached. It failed in the php-css-parse so it was probably due to the SCSS compilation.

Might be fixed in newer versions, but cannot test this on that system.

### Actual behaviour

Out of memory error.

### How to reproduce

see above.

Might also be related to certain plugin and Shopware version combinations. But no matter the combination this should not be an issue. Especially, not with such a high limit.

**Comment by shyim** [comment]
We should try to set a higher memory limit on the fly. See example from Shopware 5
https://github.com/shopware/shopware/blob/5.7/engine/Shopware/Components/MemoryLimit.php#L34

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
