### ISSUE TITLE
OneToManyAssociation doesn't take another column as localField. It only accepts 'id' as localField for fetching the child relations.

### ISSUE THREAD

**Issue by nidheeshjbeo** [shopware/platform#2639]
### PHP Version

7.4.3

### Shopware Version

6.4.12.0

### Expected behavior

In OneToManyAssociation, if given a column other than 'id', it should take the child using it. 
Eg: table1 has columns id, productId, and use productId as localField, it should fetch the data from the child table using the values from productId

### Actual behavior

Even if we provide a localField column other than 'id', the Association is fetching values using getId() method and passing the uuid to match the relation.

### How to reproduce

In the EntityDefinition

`protected function defineFields(): FieldCollection
    {
        return new FieldCollection([
            new OneToManyAssociationField('PropertyName', Property::class,'referenceField','otherThanIdField')
        ]);
    }`
    
 When this is given the relation fetched will be empty due to it is taking 'id' for searching the child field in the given referenceField  of the child entity

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
