### ISSUE TITLE
Customer does not get logged out when their account is deactivated

### ISSUE THREAD

**Issue by nielstholenaar** [shopware/platform#2641]
### PHP Version

7.4

### Shopware Version

6.4.14

### Expected behaviour

The session is terminated and the customer is redirected to the homepage. A message will also be displayed.

### Actual behaviour

The customer stays logged in and is able to proceed to the checkout.

### How to reproduce

- Create a new account and log in.
- Deactivated the account via the Shopware admin area.
- Return back to the storefront
- Visit the /account page. Or try to add a product to the shopping cart.

**Comment by keulinho** [comment]
@edip123 maybe interesting

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
