### ISSUE TITLE
Cart Errors get entirely cleared on cart confirm page

### ISSUE THREAD

**Issue by r4pt0s** [shopware/platform#2647]
### PHP Version

7.4

### Shopware Version

6.4.13.0

### Expected behaviour

Cart errors if there are some for grabbing them in the template and displaying them persistent to the customer as long as the errors are not resolved by the customer.

### Actual behaviour

page.cart.errors is empty although there are some errors.
This is related to this line in the CheckoutController

https://github.com/shopware/platform/blob/a215f5e16f22fbacebb107f8e6114873c2673e99/src/Storefront/Controller/CheckoutController.php#L163

Instead of being able using the errors.blockOrder like it is done in

https://github.com/shopware/platform/blob/a215f5e16f22fbacebb107f8e6114873c2673e99/src/Storefront/Resources/views/storefront/page/checkout/confirm/index.html.twig#L216
You actually can't use it anymore because it doesn't exist anymore at the time of rendering the template. 

### How to reproduce

Insert customer data which is clearly not valid due to default validation.
Go to the checkout/confirm page and place the order although the button should be blocked.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
