### ISSUE TITLE
Wrong creating of navigation page seo urls 

### ISSUE THREAD

**Issue by michnhokn** [shopware/platform#2656]
### PHP Version

8.0

### Shopware Version

6.4.13

### Expected behaviour

When I create a category from type `link` no seo url should be created.

### Actual behaviour

When I create a category from type `link` a seo url is created!
This breaks seo urls in general if a landing page with the same seo url existists.
For example `/impressum` as landing page and `Impressum` as a link catgeory in the service menu to the landingpage.

### How to reproduce

Create a landing page with a seo url which is the same as a to level category with type link.
Create the landing page first and then the category. If you open the seo url now in the storefront a 404 error occurs.
If you click the category in the storefront which should link to the landing page, you will see the technical url.

This can be fixed adjusting the `prepareCriteria()` method in the file: `storefront/Framework/Seo/SeoUrlRoute/NavigationPageSeoUrlRoute.php`
```` php

 $criteria->addFilter(new MultiFilter(MultiFilter::CONNECTION_AND, [
    new EqualsFilter('active', true),
    new NotFilter(NotFilter::CONNECTION_OR, [
        new EqualsFilter('type', CategoryDefinition::TYPE_FOLDER),
         new EqualsFilter('type', CategoryDefinition::TYPE_LINK),
     ]),
]));
````

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
