### ISSUE TITLE
Editing address during checkout in modal, does not show potential errors but closes modal, e.g. FEATURE_NEXT_15957 with invalid VAT ID format

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2666]
### PHP Version

7.4

### Shopware Version

6.4.14.0

### Expected behaviour

If the address modal during checkout has errors, it should not close the modal but instead show the errors, so the user can fix the errors and save again.

### Actual behaviour

Upon an error during address save (during checkout), the modal is closed, and any address changes are lost.

### How to reproduce

Easiest way to verify is by enabling FEATURE_NEXT_15957, enabling VAT ID format validation for the country and entering a wrong VAT ID. 

The address is currently not saved, modal is closed and no error is shown.

**Comment by nexxome** [comment]
There are also two entries on the Issuetracker for this problem:
https://issues.shopware.com/issues/NEXT-19839
https://issues.shopware.com/issues/NEXT-22451

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
