### ISSUE TITLE
companyPhone missing in DocumentConfiguration

### ISSUE THREAD

**Issue by applifaction** [shopware/platform#2672]
### PHP Version

8.x

### Shopware Version

6.4.x

### Expected behaviour

The document configuration value companyPhone can be set by the Admin UI, but is not accessible by code. 

```
/* @var $documentConfiguration \Shopware\Core\Checkout\Document\DocumentConfiguration */ 
$documentConfiguration->companyPhone /* should be defined */
```

### Actual behaviour

```
/* @var $documentConfiguration \Shopware\Core\Checkout\Document\DocumentConfiguration */ 
$documentConfiguration->companyPhone /* is not available */
```

### How to reproduce

```
/* @var $documentConfiguration \Shopware\Core\Checkout\Document\DocumentConfiguration */ 
/* Try to access: */ $documentConfiguration->companyPhone
```

**Comment by applifaction** [comment]
The companyPhone is stored here, but is not accessible by code: 

![image](https://user-images.githubusercontent.com/9271838/188431506-eb1cf071-a829-49a3-9ac1-0683d446954f.png)

Just add following lines to fix the issue: 

![image](https://user-images.githubusercontent.com/9271838/188431281-1db1ce41-0cfb-46f2-8e63-70304464b169.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
