### ISSUE TITLE
EntityWriteEvent/EntityBeforeWrittenEvent similar to EntityWrittenEvent

### ISSUE THREAD

**Issue by ts-mothership** [shopware/platform#2677]
### Please describe the feature you would like to see implemented.

I'd like you to revisit the topic from #1971. 

We have a use case for one of our customers where we need to enrich the newsletter recipient data with additional information. But we don't want to overwrite/decorate all places where newsletter information is written: NewsletterSubscribeRoute, Confirm, Unsubscribe, Checkbox in Customer Account, while doing Registration, while creating an order, other custom pages, or even save events from administration. We don't want to manage all those different entrypoints.

Instead we'd like to rely on a central EntityWriteEvent/EntityBeforeWrittenEvent similar to EntityWrittenEvent where we can enrich the newsletter information.

We tried using `PreWriteValidationEvent`, but it's handing updates and inserts differently (especially custom_fields are JsonUpdateCommands only when doing updates). We cannot use the `EntityWrittenEvent` because saving data in there would create a recursion loop.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
