### ISSUE TITLE
Copied Layouts from the Admin-Dashboard can not be renamed

### ISSUE THREAD

**Issue by LouisEiermann** [shopware/platform#2678]
### PHP Version

does not matter

### Shopware Version

Administration 6.4.13.0 

### Expected behaviour

Copying a layout should lead to a new layout which should be renameable because thats the only way to distinguish the new layout in a meaningful way

### Actual behaviour

Copying a layout will lead to a new layout with the original name plus " - copy " , which makes them kinda useless because they can afterwards not really be distinguished in a meaningful way

### How to reproduce

Copy a layout in the admin dashboard

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
