### ISSUE TITLE
Improvement of loading plugins in Shopware admin area

### ISSUE THREAD

**Issue by romanWienicke** [shopware/platform#2696]
### Please describe the feature you would like to see implemented.

Hi, 

**Improvement 1:**
If a plugin has an error the whole plugin list is not shown and "no plugins installed" is displayed. Can you please change the loading of the plugins, so if a plugin throws an error the plugin is marked as "has error" instead of skipping the whole list.

**Imporvement 2:**
Updating plugins looks like an async operation an the plugin is shown as "updated" - but some seconds later the whole page is reloaded. Can you either add an "update all / selected plugins" or change the update process so the page is reloaded or it is done with JavaScript.

best,
Roman

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
