### ISSUE TITLE
upsertType in customFieldService builds wrong json

### ISSUE THREAD

**Issue by schnappenberger** [shopware/platform#2700]
### PHP Version

7.4

### Shopware Version

6.4.15.1

### Expected behaviour

Calling upserType inserts a new type in the $typeStore with correct structure

### Actual behaviour

Structure is wrong because of line 143

        $typeStore[name] = { ...$typeStore[name], ...{ configuration } };

Has to be

        $typeStore[name] = { ...$typeStore[name], ...configuration  };

### How to reproduce

Try to add a new customFieldType by a custom plugin via the upsertType method.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
