### ISSUE TITLE
NEXT-24031 Automatic promotion results in 502, because of customer loading

### ISSUE THREAD

**Issue by michielkalle** [shopware/platform#2725]
### PHP Version

7.4

### Shopware Version

6.4.6.0

### Expected behaviour

PermittedAutomaticPromotions gives a 502 in the cart when there are a lot of customers (30.000+).

### Actual behaviour

If there is a automatic promotion it must return the promotion in a decent time.

### How to reproduce

When creating a promotion that is added automatic, it will load all customers when calling the `/widgets/checkout/info' and the cart itself. This will create great problems when having a lot of customers. In the end, it ends with a 502 when having 30.000+ customers.

Example promotion:
General
- Max total uses: unlimited
- Max user per customer: 1
- active: true

Conditions
- Code options: No promotion required
- SalesChannel: connected to one
- Prevent combitation with other promotions: true
- Do not combine with: nothing
- Custumer rules: nothing
- Shopping cart rules: nothing

Discount
- Apply to: cart
- Apply to a specific range of products only: false
- Type: absolute
- Value: 5

The problem is in the property `requiredDalAssociations` of the `Shopware\Core\Checkout\Promotion\Cart\PromotionCollector`.
It will add 'personaCustomers' but that will load a manyToMany over an extension and load all customers every call to the cart.
In the optimal situation, you don't want to load customers when you are not restricting on customers in the promotion.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
