### ISSUE TITLE
Store API - Send password recovery email and register customer route should not require a context token (maybe others), should they?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2741]
### PHP Version

8.1

### Shopware Version

6.4.15.2

### Expected behaviour

The send password recovery email should work without a context token, after all the language can be selected using the corresponding header and the token would not really help here, after all the user wants to recover their password.

same for register customer. and maybe others.

### Actual behaviour

Wtih the fix for NEXT-9205 a context token required annotation (no a route defaults attribute) has been added to the SendPasswordRecoveryMailRoute.

However, there is no need to have a valid context token during password recovery and during registration. Maybe I get one during their response but it should not be needed beforehand after all language selection can happen with the corresponding header and more is not needed for anonymous users to recover their password.

Also, some other routes should probably require a valid token like e.g. ContextSwitchRoute which weirdly does not require a context token.

If for some reason you indeed want to require it, maybe add a corresponding documentation and how to best get one without requiring unnecessary requests. Also way do some routes like the switch context route not require it.

### How to reproduce

Try to call the send password recovery store api route without a context token.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
