### ISSUE TITLE
Allow changing shipping method per order after order creation

### ISSUE THREAD

**Issue by ayZagen** [shopware/platform#2743]
### Please describe the feature you would like to see implemented.

The title describes the request.

In cases of some stores work with multiple shipping companies and shipping company selection is not a customer option, shopware operators/admins should be able to change shipping method after order receival.

Thanks

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
