### ISSUE TITLE
Media Manager: Jump to containing folder

### ISSUE THREAD

**Issue by amenk** [shopware/platform#2786]
1. Search for media file in the full text / search bar
2. Result is displayed
3. But you don't know in which media folder the found file(s) is/are in

Feature request:

Add an additional Context Menu entry "Jump to containing folder" and/or a tooltip with the folder path.

**Comment by amenk** [comment]
Comments on the idea are welcome, we might be able to implement this and provide a pull request.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
