### ISSUE TITLE
featurelineItem.payload.features is not empty not working

### ISSUE THREAD

**Issue by labtrix-media** [shopware/platform#2790]
### PHP Version

8

### Shopware Version

6.4

### Expected behaviour

{% if lineItem.type == PRODUCT_LINE_ITEM_TYPE and lineItem.payload.features is not null %} is still jumping inside the if because is not **null** does not work and causes output of empty div with margin space.

Instead i use is not **empty** which works.

### Actual behaviour

{% if lineItem.type == PRODUCT_LINE_ITEM_TYPE and lineItem.payload.features is not null %} is still jumping inside the if because is not **null** does not work and causes output of empty div with margin space.

Instead i use is not **empty** which works.

### How to reproduce

{% if lineItem.type == PRODUCT_LINE_ITEM_TYPE and lineItem.payload.features is not null %} is still jumping inside the if because is not **null** does not work and causes output of empty div with margin space.

Instead i use is not **empty** which works.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
