### ISSUE TITLE
Deleting sales channel returns 500 error (Foreign key)

### ISSUE THREAD

**Issue by heydavee** [shopware/platform#2794]
### PHP Version

8

### Shopware Version

6.4.16.0

### Expected behaviour

After selecting 'Delete Sales Channel' it should get deleted

### Actual behaviour

Redirect to dashboard with no error messages showing up. Looking into dev console shows a 500 network error:

> An exception occurred while executing 'DELETE FROM `sales_channel` WHERE id = ?' with params [\"\\x06\\xae\\xa3\\x91\\x5d\\xe0\\x44\\xad\\x82\\xa0\\xfc\\x87\\x17\\xbe\\x9b\\x84\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`xxx`.`customer`, CONSTRAINT `fk.customer.sales_channel_id` FOREIGN KEY (`sales_channel_id`) REFERENCES `sales_channel` (`id`) ON `UPDATE CASCADE)

### How to reproduce

I could delete some sales channel but this one did not work. So not sure how to reproduce it

**Comment by flkasper** [comment]
The error message already shows the explanation:
If a customer has been created/registered in a SalesChannel, the SalesChannel is linked there (foreign key) and is therefore (currently?) no longer deletable.
It is possible that there are also other links.

In order for the SalesChannel to be deleted, this link must first be changed to another SalesChannel.
But this would require a delete wizard, since it can't be done automatically.

**Comment by heydavee** [comment]
Thanks. After deleting orders and customers from this old sales channel in our dev environment, we could delete the old sales channel aswell.
