### ISSUE TITLE
Product Indexer with variants still not usable [Allowed memory size of ... bytes exhausted]

### ISSUE THREAD

**Issue by moorl** [shopware/platform#2795]
### PHP Version

8.1

### Shopware Version

6.4.16

### Expected behaviour

As discussed topic in the forum:

- https://forum.shopware.com/t/performance-optimierung-indexierung/72250
- https://forum.shopware.com/t/dalindex-elasticsearch-resultiert-mit-allowed-memory-size-exhausted/72138/4
- https://forum.shopware.com/t/memory-limit-cronjob/92448/4

The product indexer ist still not usable.

I've seen some changes on v6.4.11 but the issue is still not solved.

Customer shops with many product variants can't use Shopware 6 if they don't got tons of memory.

The product indexer should not stop indexing depending by the amount of variants.

Possible solution:

- Create/use ENV/config var to limit the child-product ids @ https://github.com/shopware/platform/blob/d63843cea42f095651e418fe96a207489fad5255/src/Core/Content/Product/DataAbstractionLayer/ProductIndexer.php#L293
- Ignore child products when run dal:refresh:index (prevent double indexing)

### Actual behaviour

- PHP run out of memory
- Variant products are indexed twice

### How to reproduce

- Create a product with many variants
- Run dal:refresh:index

**Comment by heydavee** [comment]
Hey, i got the same issue. All indexing is still progressing. When checking the network tab in the backend i always see a 500 error popping in.
`Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 1155072 bytes)`

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
