### ISSUE TITLE
BUG: Watch task uses last compiled theme for variables and random theme for theme files instead of specifying a corresponding sales channel

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2803]
If one has multiple themes accross multiple sales channel, the current watch task fails completely as `theme:compile` always compiles all themes, so the variables in the `theme-variables.scss` are the last ones compiled which can be any theme.
Furthermore, the `theme:dump` to dump `theme-files.json` in the watch task supports theme ID to dump the files for a corresponding theme, but this is completely ignored here (argument not provided).

What you should do instead is add a sales channel ID (or name, would add support for both) to theme:dump and theme:compile and call both at the beginning of the watch task by providing the sales channel ID which then only compiles the theme for that sales channel, furthermore it will dump the theme files of that same theme (sales channel ID) and it should use the URL defined in the sales channel instead of the APP_URL. Maybe add an override THEME_URL variable or similar.

As the wrong watch file is here, I created the ticket here. not sure if it might not be a platform issue though too.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
