### ISSUE TITLE
Ellipses on several places

### ISSUE THREAD

**Issue by Magnusvb** [shopware/platform#2808]
### PHP Version

8.0.8

### Shopware Version

6.4.16.1

### Expected behaviour

Total value for the cart, full text on button for "denying" cookies and other headlines not truncated.

### Actual behaviour

At the cart icon (header) there is only three dots (...) instead of the value of the cart.
On the button "Deny" the text is "De..."
The headline (in admin) is "My Extensio..."

These are the places I have found after a quick check. Can be more.

Note: This happens in Safari Technology preview. I understand that it can be buggs in the browser - but I want to let you know anyway. In regular Safari there is no problem.

<img width="173" alt="Screenshot 2022-10-26 at 15 18 49" src="https://user-images.githubusercontent.com/99280/198036415-fc681eed-5f38-4f34-a664-6fefc7a2d8b5.png">

### How to reproduce

Use Safari Technology Preview

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
