### ISSUE TITLE
Breadcrumb disappears in certain scenarios

### ISSUE THREAD

**Issue by royandre** [shopware/platform#2814]
### PHP Version

Latest

### Shopware Version

Latest

### Expected behaviour

Always display a breadcrumb on the product page when navigating to it from a category.

### Actual behaviour

The breadcrumb disappears when navigating to a product from a category where the category is deactivated, but the product still appears as it exists in the parent category.

### How to reproduce

Create a sub-category and add a product to it. Then disable the sub-category. When navigating to the product from the main category (where the product appears), the breadcrumb disappears, as its "nearest" sub-category is disabled.

If one try to deactivate the parent, the child category becomes available in the breadcrumb, but the parent is still part of the breadcrumb, and the link goes to 404.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
