### ISSUE TITLE
Dependency true/punycode is abandoned

### ISSUE THREAD

**Issue by jonas-sfx** [shopware/platform#2818]
### PHP Version

irrelevant

### Shopware Version

any 6.x

### Expected behaviour

Should not be dependent on an abandoned piece of software.

### Actual behaviour

Depends on true/punycode
See: https://packagist.org/packages/true/punycode

### How to reproduce

Just call
`composer update --dry-run`
in your project root.

And when it tells
`Package true/punycode is abandoned, you should avoid using it. No replacement was suggested.`
than you see that warning, that I am talking about.

**Comment by keulinho** [comment]
Thanks for pointing out the issue, sadly we can not drop the dependencies in a minor release, but we will remove those dependencies in the next major version.

I created a official issue tracker ticket for that and will close this issue for now.
https://issues.shopware.com/issues/NEXT-23972

**Comment by jonas-sfx** [comment]
I see why you do not want to drop them in a minor release.
But why did you close this issue before solving it and while [NEXT-23972]( https://issues.shopware.com/issues/NEXT-23972) is still open?

**Comment by keulinho** [comment]
As we internally work with another issue tracker and not github the status on the official ticket is more accurate. There is no workflow to automatically link and resolve github issues, when we resolve the internal ticket. Therefore i closed both of the issues for now, so that they don't get stale. 
Closing as completed is not quite right, but the only other option github offers is closing as not completed which is even worse in this case as it is actually planned.

Feel free to reopen if it bothers you, but as said to watch for the state of the issue you should check the official ticket ;)
