### ISSUE TITLE
Poor error message upon coupon generation

### ISSUE THREAD

**Issue by royandre** [shopware/platform#2825]
### PHP Version

8

### Shopware Version

6.4.16.1

### Expected behaviour

A more informed and concrete error message than just "Something went wrong, while generating promotion codes. Please use the developer tools for more information.", like for example "You need to create the rules under discount before you can generate the coupon codes."

### Actual behaviour

When trying to generate coupon codes, the error "Something went wrong, while generating promotion codes. Please use the developer tools for more information." appears, which is really not helpful at all.

### How to reproduce

1. Generate new promotion codes (and do _not_ set a discount rule in advance)
2. Set a prefix "TEST", code length "5" and keep suffix blank
3. Set "10" in "Number of promotion codes"
4. Hit Generate new codes
5. The error appears

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
