### ISSUE TITLE
Add "sort by" and "sort direction" to product cross-selling in Administration

### ISSUE THREAD

**Issue by ghost** [shopware/platform#2843]
When adding cross-selling there is neither a way to decide what the cross-selling should be sorted by, nor what the sorting direction should be. This results in the default value being used in the front-end, which is sortBy: "name", sortDirection: "ASC", which often times may not be what our customers want.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
