### ISSUE TITLE
Cross-selling sorting by position is not honored

### ISSUE THREAD

**Issue by ghost** [shopware/platform#2844]
### Please describe the feature you would like to see implemented.

When adding cross-selling without the usage of a dynamic product group, the position set is not honored. Instead, the products are sorted by the default value, which is the name of the product.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
