### ISSUE TITLE
Max Aggregation in combination with Sort leads to unexpected behaviour

### ISSUE THREAD

**Issue by TheGoobsy** [shopware/platform#2850]
### PHP Version

8.1.12

### Shopware Version

6.4.12

### Expected behaviour

I've build the following Criteria:

```php
let criteria = new Criteria()

criteria.addAggregation(
    Criteria.terms(
        'formEntries', 'id', null, null, Criteria.max('createdAt', 'forms.entries.createdAt')
    )
)
criteria.addSorting(
  Criteria.sort(
      'forms.entries.createdAt',
      'ASC'
  )
)

criteria.addSorting(sort)
```

which should result in the following SQL query:

```sql
SELECT `forms`.`id`
FROM `forms`
    LEFT JOIN `forms_entries` `forms.entries` ON `forms`.`id` = `forms.entries`.`form_id`
GROUP BY `forms`.`id`
ORDER BY MAX(`forms.entries`.`created_at`) ASC LIMIT 25;
```

### Actual behaviour

It actually results in this query:

```sql
SELECT `forms`.`id`
FROM `forms`
    LEFT JOIN `forms_entries` `forms.entries` ON `forms`.`id` = `forms.entries`.`form_id`
GROUP BY `forms`.`id`
ORDER BY MIN(`forms.entries`.`created_at`) ASC LIMIT 25;
```
The MAX gets changed to a MIN which leads to an incorrect sorting.

### How to reproduce

https://github.com/shopware/platform/blob/3260f228efd6db9ac49bf4a4d679be479c6abb2b/src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php#L172-L178

Here the MIN and MAX gets changed for every field depending on the ASC and DESC sorting, which doesn't make sense in my case, the MAX from the MaxAggregation should always be a MAX in the query, independent from the sorting direction.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
