### ISSUE TITLE
Slow /api/product/{productId}/options request

### ISSUE THREAD

**Issue by ascheider** [shopware/platform#2855]
### PHP Version

8.0

### Shopware Version

6.4.14.0

### Expected behaviour

The variant options request is very slow.
Currently we have 78396 database entries in product_option table.
If we query /api/product/{productId} endpoint, we have fast response time
![Variant](https://user-images.githubusercontent.com/6016485/203070360-918aabca-23af-4b97-a81a-9f148215aa50.png)
But in we query only the /options, request takes more than 3 Minutes
![Slow options](https://user-images.githubusercontent.com/6016485/203070522-66e5a452-2068-4e6a-a9cd-37b0fb762968.png)
We tested the request on multiple projects with the same result.

### Actual behaviour

Subrequest for the variant options is slow.

### How to reproduce

1.) Create many variants, we have 78396 options in the table
2.) Query variant -> fast response
3.) Query only options -> very slow response

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
