### ISSUE TITLE
Calculated price is not always the cheapest one

### ISSUE THREAD

**Issue by vkalchenko** [shopware/platform#2873]
### PHP Version

8.1.12

### Shopware Version

6.4.17.2

### Expected behaviour

The system should pick up the lowest possible price value.

### Actual behaviour

First price rule element is always returned.

### How to reproduce

1. Go to Settings  > Rule builder
2. Create a few rules with the same priority. Condition may be set to "Always Valid" for the each rule.
3. Go to Catalogues > Products
4. Pick up some product and open Advanced Pricing tab
5. Create multiple price rules with the same pritority but with a different price value
6. Save the product
7. Open storefront product details page

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
