### ISSUE TITLE
Custom field Technical names supports spaces/blanks

### ISSUE THREAD

**Issue by royandre** [shopware/platform#2874]
### PHP Version

8

### Shopware Version

6.4.17.2

### Expected behaviour

Should simply not allow for empty spaces in technical names on custom fields.

### Actual behaviour

When creating a new custom field, it is allowed to have spaces/blanks in the Technical name.

This causes further issues down the road, when using that custom field.

### How to reproduce

Simply create a new custom field and type in a space anywhere in the Technical name field, e.g "usp product".

https://www.flowretail.no/wp-content/uploads/2022/12/shopware_issue_technicalname.png

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
