### ISSUE TITLE
Newline-Suppression is trimmed out of Product Export Templates 

### ISSUE THREAD

**Issue by jonas-sfx** [shopware/platform#2877]
### PHP Version

irrelevant

### Shopware Version

any 6.x

### Expected behaviour

In the template-files header.csv.twig and body.csv.twig 
out of the [product-export-templates](https://github.com/shopware/platform/tree/trunk/src/Administration/Resources/app/administration/src/module/sw-sales-channel/product-export-templates)
we find some `{#- -#}` at the end of most of the lines.

This should suppress the newline-character at the end of each "column" in those templates as they are made for csv-export-files.

### Actual behaviour

If you add  `{#- -#}` manually in your template later on it does really, what you expect.
BUT on its way from having those helpful chars in your twig-source-code file to get them in to your template they get lost.
Perhaps they get lost in a trim-function or anything else like that.

So you have to add them again after using the template file.

### How to reproduce

Just compare the mentioned Twig-Files and the CSV-Templates after an applying a template and look out for the missing `{#- -#}`

**Comment by wolf128058** [comment]
could be the reason for #2864

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
