### ISSUE TITLE
Plugin configuration: option to make cards collapsable and option to provide a description

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2882]
### Please describe the feature you would like to see implemented.

Inside the `<card>` element, add a new (optional) element `<description>` (similar to title).
Also add an option to make either all cards collapsable / only cards with at least x elements in it / with an attribute, e.g  `<card collapse="true">`

**Comment by Zerotask** [comment]
Also can you add html anchors (-> URL fragments) for each card so I can easily share the URL and it jumps directly to the card?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
