### ISSUE TITLE
My extensions: add an option to provide an URL

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2883]
### Please describe the feature you would like to see implemented.

It would be great to have a key inside the composer.json of a plugin to provide a URL (e. g. for a plugin documentation) which then will be shown in the admin area for my extensions

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
