### ISSUE TITLE
Empty line chart UI bug

### ISSUE THREAD

**Issue by AltayAkkus** [shopware/platform#2895]
### PHP Version

8.1.13

### Shopware Version

6.5.9999 Developer

### Expected behaviour

Show nothing, when there is no data.

### Actual behaviour

[screen-recorder-tue-dec-20-2022-15-58-33.webm](https://user-images.githubusercontent.com/7849969/208697408-5e71150f-416d-4d77-9e1f-36edcd9679d5.webm)
(Ignore the 404s my Pod crashed)

### How to reproduce

1. Go to `/admin`
2. Go to Dashboard
On a fresh instance Turnover should be empty, so you could see this.

Weird thing is: Shopware apparently uses the charts from [ApexCharts](https://apexcharts.com/) over their Vue wrapper https://github.com/shopware/platform/blob/71aa83a2bebb8b12b59d4920964bc4a4244231b1/src/Administration/Resources/app/administration/src/app/asyncComponent/base/sw-chart/index.js#L1

When I try to replicate this in plain HTML with ApexCharts CDN, it does the correct thing and leaves out the x, y and data labels, just like it should do for an empty line chart.
https://codepen.io/ldslflskflks/pen/KKBwwMr

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
