### ISSUE TITLE
Cart errors in store api should include parameters and blockOrder

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2897]
### PHP Version

8.1

### Shopware Version

6.4.18.0

### Expected behaviour

The store-api response for the cart should include parameters and blockOrder for all errors and the store api OpenAPI specification should be adjusted accordingly.

Only this way it is easily possible to have all necessary data available to output error messages. 

Furthermore, only this way it is easily possible to e.g. block the checkout completely by disabling the corresponding button, if there is a block order error.

### Actual behaviour

The store-api response for the cart includes the errors which is fine. However, the error data does not include `blockOrder` and `parameters` , except if they are object properties and not just return values of the methods (which is the case usually).

### How to reproduce

Have a cart with an error, e.g. remove the target shipping country of the sales channel after creating it, retrieve it through the store-api.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
