### ISSUE TITLE
Promotion error messages not localized

### ISSUE THREAD

**Issue by AltayAkkus** [shopware/platform#2902]
### PHP Version

trunk

### Shopware Version

trunk

### Expected behaviour

Error messages (like "End date needs to be after the start date") should be localized to the users language

### Actual behaviour

Only the english messages are shown

### How to reproduce

1. Create a random promotion and cause a error (place the end date before the start date)
2. See that the text is english

This because here
https://github.com/shopware/platform/blob/e91d42f995e192aac6f2504a950ad55fb9b13ccc/src/Core/Checkout/Promotion/Validator/PromotionValidator.php#L245-L251
and all the other `buildViolation` calls a snippet key is defined, but the snippet is not, so the default english fallback is used.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
