### ISSUE TITLE
Admin display setting in user profile

### ISSUE THREAD

**Issue by Tim-VL** [shopware/platform#2906]
### Please describe the feature you would like to see implemented.

Hi all,

In my opinion there are some setting missing in de (admin)user profile;

1. By default '25 items per page' are shown in the Admin, would be great if we can make this an option under (admin)user setting. This can be very handy with large amount of products/orders/clients.
2. Select default screen language (not interface language), if multi languages are available for the front-end.

Would be great if this can be added to SW.
Thanks,
Tim

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by Tim-VL** [comment]
I'm not the only one with this request. Now days with bigger screens a hard default limit 25 items in very poor use a screen space.

https://feedback.shopware.com/forums/942607-shopware-6-product-feedback-ideas/suggestions/47733002-increase-entry-per-page-in-catalogue-products
