### ISSUE TITLE
Nested Modal breaks the modal

### ISSUE THREAD

**Issue by marvn-r3** [shopware/platform#3183]
### PHP Version

8.2.7

### Shopware Version

6.5.2.1

### Expected behaviour

If a modal link is placed inside a modal and the user wants to open it, the nested modal should appear on top of the previous one. And if the user wants to close the top modal, it should only close the last modal that was opened, while the first opened modal should remain intact.

### Actual behaviour

If a user follows a modal link inside an opened modal, it closes the current modal and opens the new one. However, when the user wants to close the nested modal, the content disappears but the dark overlay remains. The user is unable to scroll or remove the overlay. The only solution for the user is to reload the page.

### How to reproduce

1. Pull the tested version (6.5.2.1) and leave it vanilla
2. Move to the frontend
3. Scroll down to the footer and click on "contact form"
4. (Modal for the contact form opens)
5. At the bottom of the modal follow the link "data protection information"
6. Now try to close the modal (using the X or by clicking outside the modal)
7. **Result:**Both modals disappear, only the overlay still exists and the user is forced to reload the page. Additionally, any text that may have been filled out in the contact form is lost.

**Comment by 7underlines** [comment]
This is still an issue on mobile with Shopware 6.5.8.7.
However, this has been addressed and fixed in Shopware version 6.6.0.1. For reference, see the discussion on the Shopware community Slack: 
https://shopwarecommunity.slack.com/archives/C011VFQT7GB/p1711462313645129

It is also likely that this issue will be resolved in a forthcoming 6.5.x release. For more details, you can view the commit on GitHub: https://github.com/shopware/shopware/commit/391de3ced881cf184275f9613913b5dbd90678c8

**Comment by 7underlines** [comment]
This is fixed with 6.5.8.8.
